#3501 Modul Suplemen
OpenSID/OpenSID pull request #3502
Opened 2020-08-26 18:14 UTC by afa28

Solusi untuk {perbaikan|fitur baru} terkait issue #3501

2020-08-27 03:49 UTC, eddieridwan commented on donjo-app/views/global/confirm_ttd.php
> +<?php
@afa28 , apakah sudah lihat file `donjo-app/views/global/ttd_pamong.php`?

2020-08-27 04:03 UTC, eddieridwan requested changes
@afa28 terima kasih.

Lihat komentar. Layout cetak masih bermasalah.

![cetak-suplemen](https://user-images.githubusercontent.com/249563/91382868-0b309000-e86e-11ea-8b41-ea9ad9ceb190.jpg)

2020-08-27 04:08 UTC, eddieridwan commented
@afa28 : salah link di rincian peserta:

![peserta-suplemen](https://user-images.githubusercontent.com/249563/91383151-c8bb8300-e86e-11ea-96c1-a0256f15fdfb.jpg)

2020-08-27 04:13 UTC, afa28 commented
Dari beberapa tampilan yg di screenshot, css belum trrload masih menggunakan yg lama. Bisa di clear cache dlu atau buka di chrome mode incognito.

2020-08-27 04:14 UTC, eddieridwan commented
Tautan ini juga salah:

![peserta-suplemen-2](https://user-images.githubusercontent.com/249563/91383515-a8d88f00-e86f-11ea-9a30-fe1a9279d78e.jpg)

2020-08-27 04:16 UTC, eddieridwan commented
> Dari beberapa tampilan yg di screenshot, css belum trrload masih menggunakan yg lama. Bisa di clear cache dlu atau buka di chrome mode incognito.

Sudah. Masih bermasalah.

2020-08-27 04:20 UTC, afa28 commented
Ternyata style yg sy buat tdk ikut, nanti sy coba push ulang style ubahannya.

2020-08-27 04:22 UTC, eddieridwan commented
@afa28 sekalian tambahkan info di daftar data suplemen:

![daftar-data-suplemen](https://user-images.githubusercontent.com/249563/91383927-b3475880-e870-11ea-9cd3-f043380f7e77.jpg)

2020-08-27 04:23 UTC, eddieridwan commented
Karena ada banyak perubahan, mohon anda lakukan testing secara teliti dan menyeluruh sebelum di-review ulang. Terima kasih.

2020-08-27 04:26 UTC, afa28 commented on donjo-app/views/global/confirm_ttd.php
> +<?php
sy tdk perhatikan, nanti sy coba pakai yg sdah ada.

2020-08-27 05:04 UTC, afa28 commented
> @afa28 : salah link di rincian peserta:
> 
> ![peserta-suplemen](https://user-images.githubusercontent.com/249563/91383151-c8bb8300-e86e-11ea-96c1-a0256f15fdfb.jpg)

sdah diperbaiki, penyesuaian ulang variable page.

2020-08-27 06:24 UTC, afa28 commented
> Tautan ini juga salah:
> 
> ![peserta-suplemen-2](https://user-images.githubusercontent.com/249563/91383515-a8d88f00-e86f-11ea-9a30-fe1a9279d78e.jpg)

Sudah diperbaiki

2020-08-27 07:44 UTC, afa28 commented
Krn fuction sasaran sma dgn index, maka hanya perlu dibuatkan filter sj seperti yg ada di modul program_bantuan. 

![1111](https://user-images.githubusercontent.com/57283157/91412185-9c563580-e873-11ea-927b-190d87070691.JPG)

2020-08-27 10:08 UTC, eddieridwan requested changes
@afa28 , tidak bisa update/ubah data suplemen. Saya tidak periksa yg lain setelah menemukan masalah ini.

Mohon anda periksa secara menyeluruh. Karena perubahan begitu banyak, anda perlu memeriksa setiap menu/tombol/fitur di modul Suplemen.

Setelah anda yakin setiap fungsi sudah ok, beritahu untuk direview ulang.

2020-08-27 10:45 UTC, afa28 commented
> @afa28 , tidak bisa update/ubah data suplemen. Saya tidak periksa yg lain setelah menemukan masalah ini.
> 
> Mohon anda periksa secara menyeluruh. Karena perubahan begitu banyak, anda perlu memeriksa setiap menu/tombol/fitur di modul Suplemen.
> 
> Setelah anda yakin setiap fungsi sudah ok, beritahu untuk direview ulang.

variable $data tertinggal $this->load->view('suplemen/form'); sehingga form_action nya kosong krn $data tdk terpanggil.

Krn menggunakan 1 view, sy sesuaikan ulang fuction view tambah dan ubah menjadi 1 fuction seperti di modul yg lainnya dan termasuk seperti fuction tambah dan ubah yg ada di rincian suplement.

2020-08-27 10:49 UTC, afa28 commented
style yg ditambahkan sebelumnya `padding: 0px !important;` , krn judul table akan terlu mepet dgn batas colom.

![1111](https://user-images.githubusercontent.com/57283157/91433342-57d79380-e88d-11ea-9ee8-38ba32dc2651.JPG)


![1111](https://user-images.githubusercontent.com/57283157/91433552-a4bb6a00-e88d-11ea-9ecf-09d153bca0a8.JPG)

2020-08-27 10:52 UTC, afa28 commented
issue yg mungkin perlu dibuat:
Sama halnya dengan modul yg memiliki sasaran, perlu ditambahkan kondisi pada form input jika data sudah ada maka sasaran tdk dpt di ubah seperti yg ada di program bantuan. Krn data akan menjadi rancuh ketika sasaran awal adalah penduduk dan diubah menjaadi sasaran keluarga datanya tdk ditemukan/berbeda dgn yg seharusnya.

2020-08-27 12:31 UTC, eddieridwan commented
@afa28 apakah sudah diperiksa semua fitur modul Suplemen tidak ada yg error? Supaya tidak bolak-balik.

2020-08-27 12:45 UTC, afa28 commented
> @afa28 apakah sudah diperiksa semua fitur modul Suplemen tidak ada yg error? Supaya tidak bolak-balik.

Ya, fungsi CRUD sdah di cek. Cetak/unduh. Dan link2 lainnya sdah sesuain.

Untuk test halaman bisa set $data['set_page'] = ['1', '2', '3']; jika datanya masih kurang dari 10.

2020-08-28 04:20 UTC, merged

2020-08-28 04:21 UTC, eddieridwan commented
@afa28 terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Tambah lisensi. 
2. Perjelas keterangan file di lisensi. 
3. Perbaiki beberapa judul. 
4. Hapus style duplikat. 
5. Perbaiki penulisan script.