ubah download excel menggunakan phpspreadsheet
OpenSID/OpenSID pull request #3535
Opened 2020-09-04 15:54 UTC by pandigresik

Solusi untuk perbaikan #3529

2020-09-05 00:56 UTC, eddieridwan requested changes
@pandigresik terima kasih. Tapi anda menambahkan banyak file (446 file). 

Saat ini strategi OpenSID adalah menambahkan file yg hanya dibutuhkan saja, supaya memudahkan desa yg memasang secara manual. Mohon hanya tambahkan file dari library Excel tersebut yg diperlukan saja. Dan kalau mengubah library Excel, juga perlu menggantikan library yg sudah ada, supaya tidak duplikat atau tumpang tindih. 

![ubah-excel](https://user-images.githubusercontent.com/249563/92293353-44e85180-ef66-11ea-84d8-8750cb755a2b.jpg)

2020-09-05 01:04 UTC, pandigresik commented
saya hanya mengubah 2 file sja, sisanya 444 file merupakan file dari library bawaan yang kami download menggunakan composer untuk kemudahan. library yang digunakan adalah https://github.com/PHPOffice/PhpSpreadsheet

2020-09-05 01:05 UTC, pandigresik commented
file library phpspreadsheet semuanya masuk ke folder vendor

2020-09-05 01:06 UTC, eddieridwan commented
Saat ini kita belum menggunakan composer. Dan walaupun masuk ke folder vendor, tetapi membuat ukuran repo (dan download zip) membengkak.

2020-09-12 13:27 UTC, eddieridwan commented
@pandigresik terima kasih. Penggantian library excel alternatif telah juga dikirim oleh @fusionid pada https://github.com/OpenSID/OpenSID/pull/3551, menggunakan https://opensource.box.com/spout/ yg lebih ringan. Jadi pull request ini bisa ditutup.

2020-09-12 13:27 UTC, closed without merging