Fix: penduduk pendatang pada saat cetak KK #3527
OpenSID/OpenSID pull request #3539
Opened 2020-09-06 05:32 UTC by yonathanrizky

Solusi untuk perbaikan terkait issue #3527
Menampilkan status penduduk pendatang pada saat cetak KK

2020-09-06 10:59 UTC, eddieridwan requested changes
@yonathanrizky terima kasih. Lihat komentar untuk perubahan yg diperlukan.

2020-09-06 10:59 UTC, eddieridwan commented on donjo-app/models/Keluarga_model.php
> +			WHERE status_dasar = 1 AND id_kk = ?";
@yonathanrizky , kriteria `status_dasar = 1` tidak bisa dihapus, karena anggota KK harus penduduk tetap. Solusi yg perlu diterapkan untuk issue ini adalah: status penduduk yg ditambahkan ke KK harus diganti menjadi penduduk tetap.

2020-09-06 12:11 UTC, yonathanrizky commented on donjo-app/models/Keluarga_model.php
> +			WHERE status_dasar = 1 AND id_kk = ?";
terima kasih pak @eddieridwan untuk kriteria status_dasar = 1 sudah saya kembalikan ke kondisi sebelumnya, untuk file Keluarga, apakah perlu dibuatkan PR baru pak? karna saya baru tau, kalau form status kependudukan ternyata jadi satu dengan form penambahan anggota keluarga, sehingga form status kependudukan di form penambahan anggota keluarga tidak muncul, tapi sudah saya betulkan dengan PR yang ini
![WhatsApp Image 2020-09-06 at 19 02 40](https://user-images.githubusercontent.com/58940381/92325422-c75f3700-f074-11ea-8c24-0570191c6d6e.jpeg)

2020-09-07 01:38 UTC, eddieridwan commented on donjo-app/models/Keluarga_model.php
> +			WHERE status_dasar = 1 AND id_kk = ?";
Pilihan solusi untuk issue https://github.com/OpenSID/OpenSID/issues/3527 :
1. Pada waktu menambah anggota baru ke KK, batasi hanya pilihan penduduk dengan status tetap. Atau
2. Pada waktu menambah anggota baru ke KK, sediakan pilihan semua penduduk lepas (yaitu yg bukan anggota KK). Kemudian kalau ditambahkan, ubah status penduduknya secara otomatis menjadi penduduk tetap.

Yg lebih tepat sesuai pengertian administrasi desa, adalah pilihan (1). Karena seharusnya penduduk pendatang atau tidak tetap tidak dimasukkan ke dalam KK di desa ybs. Yaitu ubah dulu status penduduk yg akan ditambahkan menjadi tetap dulu. 

Kasus menambah anggota KK biasanya karena: kelahiran baru, famili yg ikut KK, nikah. Semua kasus tersebut menyangkut penduduk tetap.

2020-09-07 01:40 UTC, eddieridwan commented on donjo-app/models/Keluarga_model.php
> +			WHERE status_dasar = 1 AND id_kk = ?";
@yonathanrizky , silakan anda ubah PR ini supaya menyesuaikan dengan solusi (1) di atas. Yaitu, di form untuk menambah anggota baru dari penduduk yg sudah ada, batasi pilihan pada penduduk lepas yg berstatus tetap.

2020-09-07 03:28 UTC, yonathanrizky commented on donjo-app/models/Keluarga_model.php
> +			WHERE status_dasar = 1 AND id_kk = ?";
@eddieridwan baik pak, untuk issue #3527 nanti saya ganti dengan solusi nomor 1

2020-09-07 09:54 UTC, eddieridwan commented
@yonathanrizky kalau siap direview ulang, mohon diberitahu.

![minta-direview](https://user-images.githubusercontent.com/249563/92375006-de208f00-f143-11ea-9516-0fc0550fafdf.jpg)

2020-09-07 10:52 UTC, yonathanrizky commented
> @yonathanrizky kalau siap direview ulang, mohon diberitahu.
> 
> ![minta-direview](https://user-images.githubusercontent.com/249563/92375006-de208f00-f143-11ea-9516-0fc0550fafdf.jpg)

siap pak, terima kasih sudah di beri tau, sudah request untuk di review ulang pak

2020-09-07 11:41 UTC, afa28 reviewed
Sy tdk sempat testing, cuma lihat sekilas sj. Silahkan di coba dlu.

2020-09-07 11:41 UTC, afa28 commented on donjo-app/models/Referensi_model.php
>  	}
kalau parameter $id (unik) pasti hasilnya cuma 1 sehingga lebih baik menggunakan row_array(), tp krn fuction digabung menjadi 1 mungkin ditambahkan limit(1) jika paramter $id tdk kosong.

2020-09-07 11:41 UTC, afa28 commented on donjo-app/models/Referensi_model.php
> +
Jadikan 1 baris sj klw cuma 1 kondisi.

```
if (!empty($kecuali)) $this->db->where("id NOT IN ($kecuali)");

if (!empty($id)) $this->db->where(['id' => $id]);
```

2020-09-08 11:36 UTC, eddieridwan requested changes
@yonathanrizky terima kasih. Tetapi solusi yg diperlukan juga perlu memastikan penduduk pendatang tidak terpilih menjadi anggota KK. 

![tambah-anggota](https://user-images.githubusercontent.com/249563/92471378-38405380-f21b-11ea-9703-bdf2ec432fc1.jpg)
![tambah-anggota-tetap](https://user-images.githubusercontent.com/249563/92471401-41312500-f21b-11ea-88e0-51baa6f8d7e4.jpg)

2020-09-08 13:29 UTC, yonathanrizky commented
baik pak, betulkan dulu pak

2020-09-09 05:09 UTC, merged

2020-09-09 05:14 UTC, eddieridwan commented
@yonathanrizky terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Perbaiki `referensi_model->list_data()` supaya lebih umum. Mohon selalu usahakan penambahan script dibuat umum kalau relevan.
2. Batasi pengisian kk baru hanya boleh status penduduk TETAP.  Mohon periksa semua form terkait supaya juga diperbaiki.
3. Perbaiki penulisan script sesuai aturan. Mohon lebih teliti mengikuti aturan penulisan script di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script
4. Status penduduk yg anggota KK tidak dapat diubah. Supaya penduduk TETAP yg anggota keluarga tidak diubah statusnya.

Lihat commit 04669c5faec709b4e09d7d410f05be3c47562336 untuk memeriksa perubahan yg saya buat.