Menambahkan fitur pencarian NIK/KK lebih dari satu NIK/KK
OpenSID/OpenSID pull request #3547
Opened 2020-09-08 13:28 UTC by yonathanrizky

Solusi untuk fitur baru terkait issue #3422

Maksimal 20 Nomor NIK / KK
Setiap NIK / KK dipisahkan dengan tanda koma (,)
contoh 5201142005716996,5201140706966997,5201140705156994
Apabila NIK / KK tidak terdiri dari 16 digit, apabila salah satu NIK / KK tidak tediri dari 16 digit, maka NIK / KK tersebut tidak masuk dalam pencarian
contoh : 5201142005716996,520114070,5201140705156994
maka yang dicari hanya NIK / KK pada urutan pertama dan terakhir

![kk1](https://user-images.githubusercontent.com/58940381/92482388-c57eaa80-f211-11ea-8e0b-9f0dc38782e7.PNG)
![nik1](https://user-images.githubusercontent.com/58940381/92482393-c7486e00-f211-11ea-8ac4-3eb881c8f52d.PNG)
![nik2](https://user-images.githubusercontent.com/58940381/92482394-c7e10480-f211-11ea-8dde-c9ac3fbc14b3.PNG)
![nik3](https://user-images.githubusercontent.com/58940381/92482395-c7e10480-f211-11ea-88e3-425ecdfcc684.PNG)
![nik4](https://user-images.githubusercontent.com/58940381/92482397-c9123180-f211-11ea-9c17-68f13acf78cd.PNG)

2020-09-08 15:34 UTC, afa28 commented on donjo-app/controllers/Keluarga.php
> +	public function search_kumpulan_kk_proses()
mungkin bisa pakai fuction filter sja.

2020-09-08 15:34 UTC, afa28 commented on donjo-app/controllers/Keluarga.php
> +		$data['form_action'] = site_url("keluarga/search_kumpulan_kk_proses");
Pakai fuction filter ganti site_urlnya menjadi keluarga/filter/nama_session

2020-09-08 15:34 UTC, afa28 commented on donjo-app/views/sid/kependudukan/ajax_search_kumpulan_nik.php
> +<style>
Sebaiknya style jika bentuknya umum bisa disimpan di external sj.

2020-09-08 15:34 UTC, afa28 commented on donjo-app/models/Penduduk_model.php
> +			$cari_kumpulan_nik = $_SESSION['kumpulan_nik'];
Gunakan session yg ad di CI3, walau oenulisannya agak panjang. Atau kalau mau pendek pemanggilan sessionnya, bisa dibutkan helper _session() atau sejenisnya.

2020-09-08 15:34 UTC, afa28 commented on donjo-app/views/sid/kependudukan/ajax_search_kumpulan_kk.php
> +						<div class="row">
Gunakan div row/col jika mmang dibutuhkan.

2020-09-09 08:15 UTC, eddieridwan requested changes
@yonathanrizky terima kasih.
Perlu perubahan. Juga lihat review bung @afa28 

![pilih-kumpulan](https://user-images.githubusercontent.com/249563/92572809-3ed8d480-f2c8-11ea-92e8-c173d244a195.jpg)

2020-09-09 14:45 UTC, yonathanrizky commented on donjo-app/controllers/Keluarga.php
> +	public function search_kumpulan_kk_proses()
baik mas, akan saya pelajari dlu penggunaan fungsi filternya

2020-09-09 14:46 UTC, yonathanrizky commented on donjo-app/controllers/Keluarga.php
> +		$data['form_action'] = site_url("keluarga/search_kumpulan_kk_proses");
siap mas

2020-09-09 14:46 UTC, yonathanrizky commented
baik pak @eddieridwan nanti akan saya rubah

2020-09-09 16:38 UTC, yonathanrizky commented
Untuk menu fitur kumpulan KK sudah di pindahkan ke menu Pilih Aksi Lainnya
![image](https://user-images.githubusercontent.com/58940381/92627460-980b2d00-f2f5-11ea-8da4-db7672c566ad.png)

2020-09-10 07:13 UTC, merged

2020-09-10 07:22 UTC, eddieridwan commented
@yonathanrizky terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Bersihkan masukan kumpulan NIK dan No. KK. Mohon selalu perhatikan bahwa pengguna sering salah ketik (atau ada yg iseng sembarangan mengisi) dan perlu diantisipasi dampaknya. 
2. Pisahkan dan sederhanakan penyusunan sql kumpulan. Sebaiknya hindari penggabungan fitur dan method yang panjang.
3. Seragamkan warna tombol atas. Supaya konsisten antara Keluarga dan Penduduk.
4. Sesuaikan dengan aturan penulisan script. Perhatikan perlu ada spasi setelah koma. Hindari menambahkan attribut id di input html kalau tidak perlu

Lihat commit ad710e3347b2d92b795b234537500fce4c40aac2