Update Library Export/Import Excel - Database
OpenSID/OpenSID pull request #3551
Opened 2020-09-09 16:48 UTC by fusionid

1. Mengunakan library Spout -> https://opensource.box.com/spout/
2. Mampu memproses file dengan ukuran berapa pun.
3. Hanya membutuhkan 3MB memori untuk memproses file.
4. Mekanisme streaming membuatnya sangat cepat.
5. Support XLSX, ODS and CSV.
6. Hasil export file Xlsx lebih kecil dibanding Xls dan membutuhkan memori lebih kecil sehingga tingkat kegagalan proses import data (Timeout/Memory) bisa diminimalisir walaupun dengan jumlah data yang relatif banyak.
7. Tidak perlu konversi file lagi ke excel 2003 (xls).

Library lama Spreadsheet_Excel_Reader masih belum dihapus karena masih dibutuhkan untuk impor BIP, saat ini update hanya di fitur Export/Import Database Kependudukan saja (Xlsx OpenSID/OpenDK). Bertahap fitur impor BIP akan juga diupdate.

2020-09-10 00:24 UTC, eddieridwan reviewed
@fusionid , terima kasih. Apakah bisa batasi file yg ditambah hanya yg dibutuhkan saja?

![file-excel](https://user-images.githubusercontent.com/249563/92667627-c9184b80-f34f-11ea-902d-cb5b89cca555.jpg)

2020-09-10 03:06 UTC, fusionid commented
> @fusionid , terima kasih. Apakah bisa batasi file yg ditambah hanya yg dibutuhkan saja?

Jumlah filenya ada sekitar 145 karena developernya menggunakan metode split fungsi2 ke bebebrapa file2 kecil yg berisi hanya 1-6 fungsi saja dgn hanya beberapa row syntax.
Jumlah file bisa dikurangi dgn menghapus file2 yg sekiranya tidak akan digunakan misalnya file2 yg berhubungan dengan ODX dan CSV,  pada setiap file yg disisakan harus di edit manual pada headernya dgn menghapus link use librarynya. cara ini berpotensi menimbulkan masalah jika akan update library kedepannya.
Walaupun jumlah file banyak tetapi total penambahan ukuran file hanya +-700kb saja.

2020-09-10 11:03 UTC, eddieridwan commented on donjo-app/models/Import_model.php
> +		//if (!ctype_digit($isi_baris['nik']) OR (strlen($isi_baris['nik']) != 16 AND $isi_baris['nik'] != '0')) return 'nik salah';
@fusionid baris ini mengapa di-comment?

2020-09-10 11:09 UTC, fusionid commented on donjo-app/models/Import_model.php
> +		//if (!ctype_digit($isi_baris['nik']) OR (strlen($isi_baris['nik']) != 16 AND $isi_baris['nik'] != '0')) return 'nik salah';
> @fusionid baris ini mengapa di-comment?

Selalu tidak lolos validasi kalau baris ini diaktifkan padahal NIK sudah 16 digit

2020-09-10 13:16 UTC, eddieridwan requested changes
@fusion. Lihat komentar. Saya sudah membuat berapa perubahan untuk mengatasi beberapa masalah dan push ke branch `fusion_exim_excel`. Tapi mohon anda perbaiki masalah kerancuan looping dengan menyesuaikan looping baris lama dengan cara anda sekarang.

2020-09-10 13:16 UTC, eddieridwan commented on donjo-app/models/Import_model.php
> +      }
@fusionid , karena anda menggunakan row iterator, function `cari_baris_pertama` ini perlu disesuaikan. Cara lama menggunakan loop ini untuk memeriksa baris dan menentukan apakah akan diproses atau tidak. Cara anda sekarang memanggil function untuk setiap baris dan tidak berfungsi mencari baris pertama.

2020-09-10 13:16 UTC, eddieridwan commented on donjo-app/models/Import_model.php
> +        }
@fusionid , karena anda menggunakan row iterator, loop ini perlu disesuaikan. Cara lama menggunakan loop ini untuk memeriksa baris dan menentukan apakah akan diproses atau tidak. Misalnya, cara anda sekarang selalu memproses baris pertama, sedangkan cara lama sengaja mengabaikan karena berisi judul kolom.

2020-09-11 02:56 UTC, pandigresik commented on donjo-app/models/Import_model.php
> +		//if (!ctype_digit($isi_baris['nik']) OR (strlen($isi_baris['nik']) != 16 AND $isi_baris['nik'] != '0')) return 'nik salah';
kemungkinan data nik berubah menjadi notasi ilmiah karena nilainya besar, misal 3525110000303938989 di excel kadang dibaca sebagai 3525898+10E. Maka sebaiknya formatnya diset menjadi text. Defaultnya excel akan menganggapnya sebagai number

2020-09-11 03:29 UTC, eddieridwan commented on donjo-app/models/Import_model.php
> +		//if (!ctype_digit($isi_baris['nik']) OR (strlen($isi_baris['nik']) != 16 AND $isi_baris['nik'] != '0')) return 'nik salah';
Saya sudah uncomment. Tidak bermasalah di saya. Tapi yg bermasalah adalah algoritma di import_model yg sekarang menjadi rancu. Lihat komentar di bawah.

2020-09-11 14:11 UTC, fusionid commented on donjo-app/models/Import_model.php
> +      }
Sudah diupdate di commit https://github.com/OpenSID/OpenSID/commit/7462fe86594fa391ddd7a57a67a84e1d79d4c8ff

2020-09-11 14:11 UTC, fusionid commented on donjo-app/models/Import_model.php
> +        }
Sudah diupdate di commit 7462fe8

2020-09-12 13:19 UTC, merged

2020-09-12 13:25 UTC, eddieridwan commented
@fusionid terima kasih. Sudah digabung ke `master` dengan perubahan:
1. Perbaiki iterasi baris import_excel() supaya benar termasuk untuk baris kosong, baris akhir dan melaporkan baris gagal. Dengan menghapus adanya iterasi baris di dalam iterasi baris.
2. Perbaiki iterasi baris pbdt_individu(). Menghapus adanya iterasi baris di dalam iterasi baris.
3. Hapus file yg tidak digunakan lagi.

Mohon nanti pada waktu konversi impor BIP menghindari adanya iterasi baris (cara lama) di dalam iterasi menggunakan `getRowIterator`. Ubah sepenuhnya menggunakan `getRowIterator`.