perbaikan Surat_model.php terkait issue #3558
OpenSID/OpenSID pull request #3559
Opened 2020-09-12 23:38 UTC by roaddee

Solusi untuk perbaikan terkait issue #3558

2020-09-12 23:44 UTC, roaddee commented
maaf pak, saya menggunakan prettier, untuk merapikan, jadi seolah2 banyak yang di edit, padahal hanya satu baris saja.

2020-09-13 03:45 UTC, eddieridwan requested changes
@roaddee terima kasih. Tapi plugin prettier yg anda gunakan membuat penulisan script tidak lagi sesuai dengan aturan penulisan script OpenSID. Mohon ulangi dengan mematikan plugin tersebut.

Kita terus berusaha supaya penulisan script OpenSID konsisten dengan aturan di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script.

2020-09-13 03:45 UTC, eddieridwan commented on donjo-app/models/Surat_model.php
> +{
Mohon TIDAK menggunakan plugin prettier, karena hasilnya tdak sesuai dengan aturan penulisan script OpenSID di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script.

2020-09-13 03:45 UTC, eddieridwan commented on donjo-app/models/Surat_model.php
> +		for ($i = 0; $i < count($data); $i++) {
Semua bentuk ini tidak sesuai dengan aturan penulisan script OpenSID yg mengikuti style guide Codeigniter.

2020-09-13 06:08 UTC, roaddee commented
pak @eddieridwan, sudah saya commit lagi, yang perbaikan, dan menyesuaikan dengan aturan penulisan script OpenSID

2020-09-13 06:08 UTC, roaddee commented on donjo-app/models/Surat_model.php
> +		for ($i = 0; $i < count($data); $i++) {
sudah saya commit lagi pak

2020-09-13 11:57 UTC, merged

2020-09-13 12:10 UTC, eddieridwan commented
@roaddee terima kasih. Sdh digabung ke `master`