Menambahkan fitur Sensor NIK / KK Issue#3193
OpenSID/OpenSID pull request #3567
Opened 2020-09-17 04:55 UTC by yonathanrizky

Solusi untuk fitur baru terkait issue 3193
Sensor Data NIK / KK pada saat cetak atau unduh
Pilihan berada pada pilihan Pilih Aksi Lainnya
Modul yang sudah di beri pilihan sensor nik / kk
- Penduduk
- Keluarga
- Rumah Tangga
- DPT
- Log Penduduk

mohon infokan apabila ada modul yg ingin di tambahkan pilihan sensor nik / kk pada saat mencetak/menguduh data.

![image](https://user-images.githubusercontent.com/58940381/93421798-8967db80-f8dc-11ea-81d3-e97d6b835d23.png)
![image](https://user-images.githubusercontent.com/58940381/93421828-95539d80-f8dc-11ea-9753-a7edc11cce0a.png)

2020-09-18 05:27 UTC, eddieridwan requested changes
@yonathanrizky , terima kasih.

Kita berusaha di mana mungkin mengurangi aksi controller terpisah, kecuali memang aksi berbeda. Dalam hal ini, sebenarnya aksinya tetap cetak/unduh -- hanya ada informasi tambahan, yaitu apakah akan disensor atau tidak.

Jadi solusi yg lebih tepat adalah mengirim paramater tambahan ke aksi terkait.

Pengiriman parameter tambahan itu bisa melalui url atau sebagai data `post`. Untuk pengiriman `post` akan diperlukan form berisi kolom untuk dicentang/dipilih (sensor atau tidak). 

Atau untuk sementara, dan lebih cepat dikirim melalui url saja. Sebagai contoh, untuk RTM, di controller `donjo-app/controllers/Rtm.php`, bisa ubah method `daftar` sebagai berikut:

```
	/*
	* $aksi = cetak/unduh
	*/
	public function daftar($aksi = '',  $privasi_nik='')
	{
		$data['main'] = $this->rtm_model->list_data($this->session->order_by, 0, 10000);
                 $data['privasi_nik'] = $privasi_nik;
		$this->load->view("sid/kependudukan/rtm_$aksi", $data);
	}
```
Di view tinggal dipanggil dengan `<?= site_url("rtm/daftar/cetak/1")?>` untuk privasi dan `<?= site_url("rtm/daftar/cetak")?>` kalau tidak. 

Jadi tidak perlu method tambahan. 

Sekalian di controller di mana method `cetak` dan `unduh` belum digabung, mohon sekalian digabung mengikuti contoh di `donjo-app/controllers/Rtm.php`.

Terima kasih.

2020-09-18 11:23 UTC, yonathanrizky commented
terima kasih atas arahannya pak @eddieridwan untuk pilihan cetak & unduh biasa atau cetak & unduh dengan privasi sebaiknya dibuatkan modal untuk pilihan tersebut atau di buat dropview seperti aksi lainnya, tapi ada dua pilihan dengan privasi atau tidak dengan privasi ?

2020-09-18 12:36 UTC, eddieridwan commented
Idealnya cetak dan unduh membuka modal dialog, di mana ada kotak yg dapat dicentang apabila NIK/No.KK ingin disensor. Kalau tidak dicentang, dicetak/unduh biasa.

2020-09-18 12:55 UTC, pandigresik commented
kalau bisa proses sensor dilakukan di level query akan lebih mudah, jadi hanya ubah query pengambilan data aja

2020-09-19 05:36 UTC, yonathanrizky commented
pilihan cetak dan unduh dengan privasi terletak pada modal
![image](https://user-images.githubusercontent.com/58940381/93659966-a800da80-fa74-11ea-8561-e1dc339bd75c.png)

2020-09-19 12:56 UTC, merged

2020-09-19 13:03 UTC, eddieridwan commented
@yonathanrizky terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Seragamkan nama file dan aksi menjadi cetak/unduh. 
2. Perbaiki penulisan script sesuai aturan penulisan.
3. Hapus script yg tidak digunakan. 
4. Sederhanakan script.
5. Perjelas modal untuk mencentang pilihan mensensor NIK/No. KK.

Perubahan dapat dilihat di commit 4d90c73c1ee91f58aa08ccba9c62e818cff87452 -- sebagai masukan untuk PR anda selanjutnya.

2020-09-20 05:48 UTC, yonathanrizky commented
@eddieridwan terima kasih pak, akan saya perbaiki lagi mengenai penulisan script nya pak