mengubah label NIAP menjadi NIPD
OpenSID/OpenSID pull request #3568
Opened 2020-09-17 06:19 UTC by pandigresik

Solusi untuk perbaikan terkait issue #3564, label bisa diatur melalui fitur setting aplikasi key sebutan_nip_desa

2020-09-18 10:16 UTC, eddieridwan requested changes
@pandigresik terima kasih. Mohon lihat komentar.

2020-09-18 10:16 UTC, eddieridwan commented on donjo-app/models/Pamong_model.php
> +		$data['daftar_perangkat'] = $this->db->select('dp.jabatan,dp.pamong_niap, dp.foto,
Perlu disesuaikan dgn aturan penulisan script: tambah spasi sesudah setiap koma pada daftar parameter.

2020-09-18 10:16 UTC, eddieridwan commented on donjo-app/models/migrations/Migrasi_2009_ke_2010.php
> +		$this->db->query("INSERT INTO setting_aplikasi (`key`,value,keterangan) VALUES ('sebutan_nip_desa','NIPD','Pengganti sebutan label niap')");
Script ini harus bisa dijalankan berkali-kali. Yaitu, periksa apakah kolom sudah ada sebelum menambah kolom baru.

2020-09-18 10:16 UTC, eddieridwan commented on donjo-app/models/migrations/Migrasi_2009_ke_2010.php
> +		$this->db->query("ALTER TABLE tweb_desa_pamong CHANGE COLUMN pamong_niap pamong_niap varchar(25) default(0)");
Error sintaks.

2020-09-18 12:48 UTC, pandigresik commented on donjo-app/models/migrations/Migrasi_2009_ke_2010.php
> +		$this->db->query("INSERT INTO setting_aplikasi (`key`,value,keterangan) VALUES ('sebutan_nip_desa','NIPD','Pengganti sebutan label niap')");
tidak ada penambahan column, ini hanya merubah panjangnya menjadi 25 saja

2020-09-18 12:53 UTC, pandigresik commented on donjo-app/models/migrations/Migrasi_2009_ke_2010.php
> +		$this->db->query("ALTER TABLE tweb_desa_pamong CHANGE COLUMN pamong_niap pamong_niap varchar(25) default(0)");
akan kami cek lagi

2020-09-18 12:59 UTC, eddieridwan commented on donjo-app/models/migrations/Migrasi_2009_ke_2010.php
> +		$this->db->query("INSERT INTO setting_aplikasi (`key`,value,keterangan) VALUES ('sebutan_nip_desa','NIPD','Pengganti sebutan label niap')");
Penambahan data ke `setting_aplikasi`, sedangkan kolom `key` harus unik. Jadi kalau ditambah (migrasi) berkali-kali akan error.

2020-09-18 13:01 UTC, eddieridwan commented on donjo-app/models/migrations/Migrasi_2009_ke_2010.php
> +		$this->db->query("ALTER TABLE tweb_desa_pamong CHANGE COLUMN pamong_niap pamong_niap varchar(25) default(0)");
`default 0`, tidak perlu ada kurungnya

2020-09-18 22:47 UTC, pandigresik commented
pada perbaikan ini saya menambahkan constraint unique dalam tabel setting_aplikasi untuk column key, saya cek di db saya hasil restore dari file contoh constraint tersebut belum ada

2020-09-18 23:58 UTC, merged

2020-09-19 00:08 UTC, eddieridwan commented
@pandigresik terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Tambah validasi batasi panjang kolom isian NIP, NIPD dan NIK di form pemerintahan desa. Mohon selalu cek validasi dan tambahkan kalau perlu.
2. Perbaiki keterangan file di info lisensi. 
3. Tambahkan cek hasil query di migrasi.

Juga perhatikan bahwa `setting_aplikasi` menyediakan pilihan di tabel `setting_aplikasi_options`. Dalam hal ini mungkin lebih baik kalau `sebutan_nip_desa` dibatasi pada pilihan ['NIPD', 'NIAP'] saja.  Mohon anda tambahkan ini kalau sempat. Lihat contoh lain di migrasi sebelumnya.