Perbaiki url modul web > artikel
OpenSID/OpenSID pull request #3572
Opened 2020-09-20 09:55 UTC by afa28

### PERBAIKAN :
1. Perbaiki url modul admin web > artikel
2. Sederhanakan komentar_lock dan artikel_lock
3. Gunakan session , query bulider CI3
4. Gunakan style table yg sama

Penyesuaian ulang untuk perubahan pd PR #3252

2020-09-22 12:58 UTC, eddieridwan requested changes
@afa28 terima kasih. Masih ada yg lolos testing anda. Salah satu adalah artikel agenda salah -- blok data agenda tidak tampil. Mohon periksa setiap aksi yg anda ubah (setiap aksi di web).

![artikel-agenda](https://user-images.githubusercontent.com/249563/93884747-a2322000-fd26-11ea-8216-f3257254b044.jpg)

2020-09-22 13:02 UTC, afa28 commented
> @afa28 terima kasih. Masih ada yg lolos testing anda. Salah satu adalah artikel agenda salah -- blok data agenda tidak tampil. Mohon periksa setiap aksi yg anda ubah (setiap aksi di web).
> 
> ![artikel-agenda](https://user-images.githubusercontent.com/249563/93884747-a2322000-fd26-11ea-8216-f3257254b044.jpg)
> 

Ok, nanti sy cek lg.

2020-09-22 13:08 UTC, afa28 commented
Sy lupa kirim nilai paramter $cat di fuction form() untuk di tampilkan di form view

<!-- Error while uploading Screenshot_2020-09-22-21-05-36-38.jpg -->

2020-09-23 03:31 UTC, eddieridwan commented
@afa28 apakah PR ini sdh siap direview ulang?

2020-09-23 03:34 UTC, afa28 commented
> @afa28 apakah PR ini sdh siap direview ulang?

Blum, sy belum balik ke kost ambil laptop. Masih di rumah teman.

2020-09-24 00:14 UTC, merged

2020-09-24 00:18 UTC, eddieridwan commented
@afa28 terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Tampilkan 404 apabila berusaha mengubah artikel yg tidak ditemukan.