Render view
OpenSID/OpenSID pull request #3580
Opened 2020-09-23 15:10 UTC by afa28

Solusi untuk {perbaikan|fitur baru} terkait PR #3575

Untuk minisidebar sy gunakan `$this->render('view', $data, TRUE);` dan yg menggunakan `$nav['tip'] = N;` sy ganti menjadi `$data['tip'] = N;`

Kalau ada temuan lain yg bermasalah, bisa langsung comment.

![2](https://user-images.githubusercontent.com/57283157/94031857-86438280-fde9-11ea-90e6-de6b8472d922.JPG)
![1111](https://user-images.githubusercontent.com/57283157/94031860-88a5dc80-fde9-11ea-8c77-9a503a7873d6.JPG)

2020-09-23 22:20 UTC, pandigresik commented
variabel minsidebar itu milik $header dalam hal ini digunakan oleh views/header, saya rasa aneh jika kita ubah nilainya melalui function render dengan menjadikannya sebagai parameter. konsep awal render adalah hanya mengubah contentnya saja. Jadi hanya focus isi content yang tengah saja tidak mengubah nilai yang akan digunakan oleh view lain ( header, nav dan footer).
Ini pendapat pribadi saja sih

2020-09-24 00:34 UTC, eddieridwan commented
@afa28 , saya setuju dengan pendapat @pandigresik . Sebaiknya property render tidak dikirim sebagai parameter, melainkan di-set secara terpisah. Lebih konsisten dengan gaya object-oriented. 

Tetapi sebenarnya, adanya `render` di `donjo-app/core/MY_Controller.php` juga kurang cocok -- karena urusan views, bukan urusan controller. Lebih konsisten kalau dibuat `layout` di views (seperti `themes/klasik/layouts/artikel.tpl.php`) untuk mengatur layout tampilan standar untuk halaman admin. Jadi nanti lebih mendekati gaya CI 4 (atau Laravel).

2020-09-24 00:35 UTC, eddieridwan requested changes
@afa28 mohon lihat komentar.

2020-09-24 04:42 UTC, eddieridwan commented
@afa28 @pandigresik , saya sudah perbaiki error yg dilaporkan di #3575. Yg keuangan menggunakan `$this->render`. Sedangkan yg database menggunakan template view `donjo-app/views/database/database.tpl.php` (`tpl` singkatan `template` seperti digunakan di view tema). Saya kira cara menggunakan view template lebih umum daripada menggunakan `donjo-app/core/MY_Controller.php` untuk mengatur layout.

2020-09-24 05:49 UTC, closed without merging