#3602 Perbaikan request_awal
OpenSID/OpenSID pull request #3603
Opened 2020-09-30 15:48 UTC by afa28

Solusi untuk {perbaikan|fitur baru} terkait issue #3602

### Perbaikan : 
1. Perbaikan request_awal.
2. Hapus function flash  dan view config.php yg tdk digunakan.

2020-10-05 06:52 UTC, eddieridwan requested changes
@afa28 terima kasih.
Tapi hasilnya error 404:

![Uploading 404_Page_Not_Found.jpg…]()

2020-10-05 08:10 UTC, afa28 commented
Sy blum coba untuk kasus .htaccess tdk di ktifkan, nanti sy perbaii lg.

2020-10-05 08:15 UTC, afa28 commented
Untuk yg sekrang work jika .htaccess dimatikan (dengan index), yg sy PR work jika .htaccess dihidupkan.

2020-10-05 08:35 UTC, afa28 commented
Sudah sy perbaiki dgn kondisi .htaccess diaktifkan dan dinonakktifkan. 

Testing di windows

2020-10-05 09:21 UTC, eddieridwan requested changes
@afa28 , masih bermasalah (beda sedikit). Juga mohon di logout jangan langsung ke login, tapi tetap pergi ke halaman default ($this->index). Cara ini lebih umum. Jadi harus klik tombol login untuk login lagi. 

![404_Page_Not_Found](https://user-images.githubusercontent.com/249563/95061980-123d9e80-0748-11eb-9195-4d33ae77fbd3.jpg)

2020-10-06 10:29 UTC, merged

2020-10-06 10:37 UTC, eddieridwan commented
@afa28 terima kasih. Tapi solusi anda masih belum benar. Sdh digabung ke `master` dengan perubahan:
1. Perbaiki `request_awal` supaya tidak diubah oleh redirect(). Kalau anda periksa script CI untuk `redirect()` di `system/helpers/url_helper.php` terlihat bahwa `request_awal` akan diubah kalau bukan url lengkap. Jadi solusinya yg berhasil adalah dengan mengubah `request_awal` menjadi url lengkap.