#3609 #3608 Tambahkan no. kk u/ sasaran penduduk dan nik u/ sasaran keluarga
OpenSID/OpenSID pull request #3611
Opened 2020-10-02 19:15 UTC by afa28

Solusi untuk {perbaikan|fitur baru} terkait issue #3609 #3608

2020-10-05 09:55 UTC, eddieridwan commented on donjo-app/models/Suplemen_model.php
> -				$suplemen['judul_terdata_info'] = 'Nama Penduduk';
@afa28 solusi anda membatasi data suplemen pada sasaran `penduduk` dan `keluarga`. Dengan solusi anda, nanti kalau juga ditambah sasaran `rumah tangga` atau `kelompok` akan memerlukan perombakan lagi.

2020-10-05 09:56 UTC, eddieridwan commented on donjo-app/models/Suplemen_model.php
> -				$suplemen['judul_terdata_info'] = 'Nama Penduduk';
Idealnya cari solusi yg nantinya tidak perlu dirombak kalau ditambah sasaran lain (seperti untuk program bantuan).

2020-10-05 10:07 UTC, eddieridwan requested changes
@afa28 mohon lihat komentar

2020-10-05 12:50 UTC, afa28 commented
Ok, sy kira sasarannya sdah tdk bakal di tambah lg.

2020-10-07 05:53 UTC, merged

2020-10-07 05:55 UTC, eddieridwan commented
@afa terima kasih. Sdh digabung ke `master`.