penambahan fitur pencarian issue#3511
OpenSID/OpenSID pull request #3647
Opened 2020-10-11 05:06 UTC by yonathanrizky

Solusi untuk fitur baru terkait issue #3511 
penambahan fitur cari pada rincian data suplemen

2020-10-11 05:27 UTC, afa28 reviewed
Tambahkan autocomplete, bisa cek di modul lain.

2020-10-11 06:05 UTC, yonathanrizky commented
> Tambahkan autocomplete, bisa cek di modul lain.

sudah saya tambahkan pak

2020-10-11 06:42 UTC, eddieridwan requested changes
@yonathanrizky , terima kasih. Autocomplete perlu dibatasi pada yg terdata saja, jadi bukan semua penduduk/keluarga.

2020-10-12 04:40 UTC, eddieridwan requested changes
@yonathanrizky terima kasih. Mohon lihat komentar.

2020-10-12 04:40 UTC, eddieridwan commented on donjo-app/models/Suplemen_model.php
> +	public function autocomplete($id_suplemen)
Tidak bisa menggunakan id_suplemen untuk menentukan apakah keluarga atau penduduk. Karena bisa ada banyak data suplemen untuk masing2 sasaran keluarga/penduduk. Jadi harus menggunakan sasaran suplemen (kolom `sasaran` di tabel `suplemen`) untuk menentukan apakah keluarga atau penduduk

2020-10-12 04:40 UTC, eddieridwan commented on donjo-app/models/Suplemen_model.php
> +	protected function search_sql($berdasarkan = '')
Sebaiknya menggunakan sasaran untuk menentukan keluarga/penduduk supaya konsisten. Juga nanti mungkin ada sasaran lain seperti rumah tangga atau kelompok.

2020-10-12 04:40 UTC, eddieridwan commented on donjo-app/controllers/Suplemen.php
>  }
Pindahkan supaya dekat dengan rincian, supaya jelas kedua method ini terkait rincian, bukan daftar suplemen utama. Beri komentar di script supaya jelas.

2020-10-12 06:57 UTC, yonathanrizky commented
> @yonathanrizky terima kasih. Mohon lihat komentar.

terima kasih pak @eddieridwan nanti akan saya perbaiki

2020-10-13 11:58 UTC, merged

2020-10-13 12:02 UTC, eddieridwan commented
@yonathanrizky terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Hapus script tidak digunakan. 
2. Buat penanganan sasaran di search_sql supaya konsisten dengan script lain. Selalu usahakan script dibuat konsisten, supaya lebih mudah dimengerti oleh programmer yg lain.

2020-10-13 12:08 UTC, yonathanrizky commented
@eddieridwan baik pak, terima kasih untuk masukannya, akan saya perhatikan lagi di PR selanjutnya