Perbaikan Form input Bobot dan Aksi Analisis pada Indikator Analisis …
OpenSID/OpenSID pull request #3648
Opened 2020-10-11 16:02 UTC by ianskids

…di modul Analisis

Solusi untuk perbaikan terkait issue #3644

2020-10-12 05:20 UTC, eddieridwan requested changes
@ianskids terima kasih. 

Tapi, setelah saya pelajari ternyata yg diberikan bobot dan aksi analisis hanya yg Pilihan (Tunggal). Yang lain otomatis diberi bobot 0 dan tidak ada aksi analisis.

Ini sesuai dengan konsep bahwa yg bisa dianalisa adalah jenis indikator seperti kepemilikan rumah yg dinilai berdasarkan jenis kepemilikan rumah seseorang (misalnya kalau rumah sendiri diberi nilai tinggi). 

Sedangkan jenis pertanyaan yg lain lebih sulit untuk diberi nilai (karena tergantung dari isiannya). Bisa saja disusun aturan supaya bisa, tapi sepertinya saat ini belum tercakup.

Jadi mohon anda kembalikan supaya bobot dan aksi analisis hanya tampil untuk Pilihan (Tunggal), sedangkan yg lain diberi bobot 0 dan aksi analisis = tidak.

2020-10-12 05:35 UTC, ianskids commented
Baik pak @eddieridwan

2020-10-13 10:58 UTC, eddieridwan requested changes
@ianskids terima kasih. Lihat komentar apa yg perlu diperbaiki.

2020-10-13 10:58 UTC, eddieridwan commented on donjo-app/models/Analisis_indikator_model.php
> -		}
Ini diperlukan, karena seperti dijelaskan, hanya Pilihan Tunggal yg diberi bobot and aksi analisis. Masukkan ini ke `validasi_data()`

2020-10-13 10:58 UTC, eddieridwan commented on donjo-app/views/analisis_indikator/form.php
> -</script>
Mengapa dihapus? Kembalikan supaya bisa menampilkan/menyembunyikan delik

2020-10-13 10:58 UTC, eddieridwan commented on donjo-app/views/analisis_indikator/form.php
> -											<div class="form-group" id="delik">
Ubah id='delik' menjadi class='delik' sesuai dengan javascript.

2020-10-13 10:58 UTC, eddieridwan commented on donjo-app/views/analisis_indikator/form.php
> -											<div class="form-group" id="delik">
Kembalikan semua delik.

2020-10-13 12:52 UTC, ianskids commented
baik pak @eddieridwan akan saya perbaiki

2020-10-14 03:02 UTC, merged

2020-10-14 03:08 UTC, eddieridwan commented
@ianskids terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Perbaki reset_form. Supaya tampilkan delik betul. 
2. Sederhanakan tampilkan delik. 
3. Perbaiki penulisan script menggunakan helper. Mohon selalu usahakan mengubah supaya menggunakan helper di view.

2020-10-14 23:55 UTC, ianskids commented
Terimakasih pak @eddieridwan sudah di gabung dengan master, baik pak akan saya usahakan sebisa mungkin