hilangkan first dari domain utama
OpenSID/OpenSID pull request #3652
Opened 2020-10-13 02:24 UTC by pandigresik

Solusi untuk perbaikan #3615

2020-10-13 21:24 UTC, afa28 commented
Untuk tahap awal mungkin cukup domain utama yg dihilangkan firstnya, krn jika langsung menghapus semua fisrt u/ semua bagian maka ada beberapa yg akan error. Contoh first/statistik, jika dihapus first maka akan memanggil controller statistik yg ada di admin.

Lakukan testing u/ mode website seperti: offline_mode atau lainnya.

2020-10-13 21:29 UTC, afa28 commented
Jika sudah siap di riview, silahkan klik request riview seperti pd gambar.

![1222222](https://user-images.githubusercontent.com/57283157/95918273-b45b2780-0dd5-11eb-9844-ef9d90fb0d13.JPG)

2020-10-14 00:58 UTC, pandigresik commented
> Untuk tahap awal mungkin cukup domain utama yg dihilangkan firstnya, krn jika langsung menghapus semua fisrt u/ semua bagian maka ada beberapa yg akan error. Contoh first/statistik, jika dihapus first maka akan memanggil controller statistik yg ada di admin.
> 
> Lakukan testing u/ mode website seperti: offline_mode atau lainnya.

mungkin bisa diinfo url yang mengalami error, karena untuk statistik, informasi_publik, gallery masih menggunakan first karena ternyata ada controller dengan nama - nama tersebut

2020-10-14 07:36 UTC, afa28 commented
menu statistik
![s1](https://user-images.githubusercontent.com/57283157/95957949-9d92f000-0e2a-11eb-893f-08e9bb40eeda.JPG)

2020-10-14 10:03 UTC, eddieridwan requested changes
@pandigresik terima kasih.

Perlu periksa dan perbaiki akses ke halaman statis melalui menu statis. Misalnya url ke statistik dan peta gagal, Jadi mohon periksa setiap halaman statis.

2020-10-14 13:02 UTC, pandigresik commented
![image](https://user-images.githubusercontent.com/1853475/95992212-eb721d00-0e57-11eb-92c7-f160b925c7e6.png)

2020-10-15 06:26 UTC, merged

2020-10-15 06:28 UTC, eddieridwan commented
@pandigresik terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Juga hapus `first` dari URL halaman statis `peta` dan `informasi_publik`