Penambahan kolom nik, KK dan Perubahan Format Alamat
OpenSID/OpenSID pull request #3678
Opened 2020-10-17 15:19 UTC by ianskids

Solusi untuk perbaikan terkait issue  #3622

2020-10-17 18:05 UTC, afa28 reviewed
Bung @ianskids , sudah sy lakukan beberapa penyesuaian yg mungkin bisa diterapkan di PR berikutnya.

Pak @eddieridwan bisa riview.

2020-10-18 06:42 UTC, eddieridwan reviewed
@ianskids @afa28 apakah sudah dicoba dengan analisis yg subjeknya Rumah Tangga dan Kelompok? Saya coba dengan Rumah Tangga, laporan hasil klasifikasi tampil kosong.

2020-10-18 06:47 UTC, eddieridwan requested changes
@ianskids @afa28 lihat komentar

2020-10-18 06:47 UTC, eddieridwan commented on donjo-app/views/global/autocomplete.php
> +</script>
Ini sebaiknya di `assets/js/script.js`, tidak sebagai partial. Untuk paramater keyword bisa gunakan data attribute, misalnya `data-keyword`, yang nantinya bisa dibaca di script js.

2020-10-18 06:49 UTC, afa28 commented
> @ianskids @afa28 apakah sudah dicoba dengan analisis yg subjeknya Rumah Tangga dan Kelompok? Saya coba dengan Rumah Tangga, laporan hasil klasifikasi tampil kosong.

Sy baru test td, data tdk ditampilkan. dan jg input data sensus/survei menampilkan kk kosong.

2020-10-18 06:50 UTC, afa28 commented on donjo-app/views/global/autocomplete.php
> +</script>
ok

2020-10-18 13:35 UTC, ianskids commented
Pak @eddieridwan dan @afa28 saya coba bisa pak, tetapi harus ada data di RTM dan Kelompok

2020-10-18 13:55 UTC, afa28 commented
> Pak @eddieridwan dan @afa28 saya coba bisa pak, tetapi harus ada data di RTM dan Kelompok

yg bermasalah itu di laporan hasil klasifikasi yg tdk muncul. Sy blum cek lg.

2020-10-19 04:35 UTC, merged

2020-10-19 04:42 UTC, eddieridwan commented
@ianskids @afa28 terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Ubah nama `combobox_wilayah.php` menjadi `filter_wilayah.php`, supaya fungsinya lebih jelas.
2. Kirim nama form sebagai parameter ke `filter_wilayah.php`, supaya lebih umum.
3. Tambah comment supaya lebih jelas. Mohon selalu tambahkan comment pada script yg berpotensi sulit dimengerti atau mudah keliru,
4. Perbaiki penulisan script.

2020-10-19 04:51 UTC, eddieridwan commented
Masalah Laporan Hasil Klasifikasi tidak tampil untuk sasaran Rumah Tangga & Kelompok, sudah dibuatkan issuenya: https://github.com/OpenSID/OpenSID/issues/3683.

Masalah ini sdh ada sebelumnya di v20.10.

2020-10-19 14:11 UTC, ianskids commented
Terimakasih sudah digabung di Master, baik Pak akan saya perbaiki