Penambahan Tombol untuk Tambah beberapa anggota kelompok sekaligus
OpenSID/OpenSID pull request #3706
Opened 2020-10-24 15:03 UTC by ianskids

Solusi untuk perbaikan terkait issue #3690

2020-10-25 07:01 UTC, eddieridwan requested changes
@ianskids terima kasih.

Tombol atas ada masalah css di laptop. Mohon diperbaiki dulu.

![kelompok-1](https://user-images.githubusercontent.com/249563/97100848-f8aac980-16eb-11eb-9f16-bab9e6b3c7e4.jpg)

2020-10-25 07:15 UTC, ianskids commented
Baik Pak @eddieridwan

2020-10-26 00:18 UTC, merged

2020-10-26 00:19 UTC, eddieridwan commented
@ianskids terima kasih. Sdh di gabung ke `master` dengan perubahan:
1. Sederhanakan script.

2020-10-26 00:40 UTC, ianskids commented
Terimakasih Pak @eddieridwan