Perbaikan perbedaan Jumlah Penerima antara Menu Admin dan Website Desa
OpenSID/OpenSID pull request #3709
Opened 2020-10-25 16:49 UTC by ianskids

Solusi untuk perbaikan terkait issue #3653

2020-10-26 01:24 UTC, eddieridwan requested changes
@ianskids terima kasih. Tapi statistik penduduk per program juga perlu disesuaikan supaya konsisten.

![bantuan-1](https://user-images.githubusercontent.com/249563/97124865-f5641c00-1785-11eb-88aa-072191460291.jpg)
![bantuan-2](https://user-images.githubusercontent.com/249563/97124869-f9903980-1785-11eb-804a-6df938e74520.jpg)

2020-10-26 01:32 UTC, ianskids commented
Baik Pak @eddieridwan

2020-10-27 01:27 UTC, eddieridwan commented
@ianskids, apakah PR ini sudah siap direview ulang?

2020-10-27 01:56 UTC, ianskids commented
Baik Pak @eddieridwan sudah bisa direview ulang

2020-10-27 05:22 UTC, merged

2020-10-27 05:25 UTC, eddieridwan commented
@ianskids terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Tambah penjelasan di statistik bantuan. 
2. Perbaiki tampilkan BUKAN PENERIMA di bantuan penduduk/keluarga dari peserta aktif saja.

Statistik bantuan masih banyak yg bermasalah. Nanti dibuatkan issue tambahan.