Menentukan nilai default masa berlaku surat
OpenSID/OpenSID pull request #3733
Opened 2020-11-08 12:13 UTC by yonathanrizky

Menentukan nilai default masa berlaku surat issue #1763

2020-11-09 11:26 UTC, eddieridwan requested changes
@yonathanrizky terima kasih. 

Setting masa berlaku perlu dibuat untuk masing-masing jenis surat. Awalnya gunakan setting default. Karena bisa berbeda tergantung jenis surat.

![masa-berlaku](https://user-images.githubusercontent.com/249563/98535682-9f8d8900-22da-11eb-8e00-93eaa4b0375e.jpg)

2020-11-10 04:52 UTC, yonathanrizky commented
> @yonathanrizky terima kasih.
> 
> Setting masa berlaku perlu dibuat untuk masing-masing jenis surat. Awalnya gunakan setting default. Karena bisa berbeda tergantung jenis surat.
> 
> ![masa-berlaku](https://user-images.githubusercontent.com/249563/98535682-9f8d8900-22da-11eb-8e00-93eaa4b0375e.jpg)

baik pak @eddieridwan nanti akan saya ubah, terima kasih

2020-11-10 10:26 UTC, eddieridwan commented
> untuk masa berlakunya apakah perlu diberi pilihan juga pak? seperti dalam satuan Hari, Bulan dan Tahun?
> terima kasih

Bisa sediakan dua kolom isian:
1. isian bilangan min 1, maks 31
2. pilihan satuan Hari/Bulan/Tahun

Sehingga admin bisa buat setting seperti 7 hari, atau 1 bulan, atau 6 bulan atau 1 tahun, dsbnya.

2020-11-12 00:59 UTC, eddieridwan commented
@yonathanrizky , apakah PR ini sudah siap untuk direview ulang?

2020-11-12 01:10 UTC, yonathanrizky commented
belum siap pak @eddieridwan , maaf saya baru bisa kerjakan di sabtu / minggu pak, karena deadline pekerjaan sedang banyak

2020-11-13 10:14 UTC, merged

2020-11-13 10:19 UTC, eddieridwan commented
@yonathanrizky terima kasih. Sdh digabung ke `master` dengan perubahan:
1. Perbaiki migrasi, termasuk mengatur supaya masa berlaku default 1 bulan. Mohon ikuti penjelasan di https://github.com/OpenSID/OpenSID/wiki/Menambah-Migrasi-Database
2. Ganti versi database, supaya migrasi dijalankan otomatis. Juga dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Menambah-Migrasi-Database
3. Sederhanakan script penghitungan `tgl_akhir` menggunakan data attribute, dan gunakan kode standar moment untuk minggu ('w'). 
4. Gunakan `referensi_model.php` untuk mengelola daftar kode masa berlaku. `referensi_model` memudahkan pengelolaan daftar kode.

2020-11-13 11:19 UTC, yonathanrizky commented
baik pak @eddieridwan kedepannya akan saya perbaiki lagi mengenai aturan migrasi database dan penggunaan referensi model