fix: perbaiki style judul artikel
OpenSID/OpenSID pull request #3776
Opened 2020-11-22 12:44 UTC by yonathanrizky

Solusi untuk perbaikan terkait issue #3762

2020-11-23 07:18 UTC, eddieridwan requested changes
@yonathanrizky terima kasih. Mohon lihat komentar.

2020-11-23 07:18 UTC, eddieridwan commented on themes/hadakewa/css/first.css
> +	text-transform: capitalize;
@yonathanrizky di issue https://github.com/OpenSID/OpenSID/issues/3762, diminta supaya `sesuaikan saja dengan apa yang ditulis di admin web artikel judulnya`.

Sebenarnya masalah seperti ini kebanyakan adalah sesuai selera. Solusi anda mengubah dari uppercase menjadi capitalize. Tapi belum tentu semua setuju. 

Sebaiknya permintaan seperti ini yg bersifat `tergantung selera` sebaiknya dilempar dulu ke forum komunitas di https://www.facebook.com/groups/OpenSID, untuk mendapatkan masukan dan persetujuan komunitas.

Sering solusinya adalah bukan memaksa semua mengikuti satu cara, tetapi menyediakan pengaturan supaya masing2 desa bisa memilih sendiri gaya judul yg diinginkan.

2020-11-23 07:23 UTC, eddieridwan commented on themes/hadakewa/css/first.css
> +	text-transform: capitalize;
@yonathanrizky perhatikan bahwa di panduan wiki, https://github.com/OpenSID/OpenSID/wiki/Mengubah-Penampilan-Web, dijelaskan cara pengguna bisa mengubah tampilan web dengan menambah css sendiri di folder desa -- termasuk mengubah tampilan tema hadakewa.

Jadi dalam kasus ini, perubahan yg perlu dibuat bukan untuk mengubah css menjadi `capitalize`, tapi cukup mengubah css supaya judul artikel bisa lebih mudah diubah oleh pengguna melalui css tambahan di folder `desa`.

2020-11-23 07:25 UTC, eddieridwan commented on themes/hadakewa/css/first.css
> +	text-transform: capitalize;
Kemudian, di folder `desa-contoh` menyediakan contoh css untuk mengubah case judul dari uppercase menjadi capitalize.

2020-11-23 15:58 UTC, yonathanrizky commented
baik pak @eddieridwan akan saya pelajari dahulu dan saya perbaiki

2020-11-27 23:27 UTC, hasap86 commented
solusi pertama saya setuju dengan pak @eddieridwan supaya judul sesuai dengan apa yg diisi oleh operator di web admin aja, jadi bisa sesuaikan sendiri gaya penulisannya sesuai apa yang diketik, jadi untuk pengguna awam tidak harus merubah rubah pada hosting pada css

2020-11-28 03:16 UTC, eddieridwan commented
@yonathanrizky , sesuai usul @hasap86 , default diubah supaya tidak ada `text-transform`, supaya tampil sebagaimana dimasukkan oleh operator. Kemudian di `desa-contoh` sediakan contoh pengubahan tampilan supaya `capitalize` semua.

2020-11-28 11:43 UTC, eddieridwan commented
@yonathanrizky , apakah sudah siap direview ulang?

2020-11-28 12:52 UTC, yonathanrizky commented
> @yonathanrizky , apakah sudah siap direview ulang?

sudah siap pak, mohon maaf, saya baru sempat untuk memperbaiki PR nya

2020-12-03 04:50 UTC, merged

2020-12-03 04:53 UTC, eddieridwan commented
@yonathanrizky terima kasih. Sdh digabung ke `master`.