#1278 EXport dan Import peserta program bantuan
OpenSID/OpenSID pull request #3842
Opened 2020-12-21 05:23 UTC by afa28

Solusi untuk {perbaikan|fitur baru} terkait issue #1278

### PERBAIKAN :
1. Perbaiki hapus data terpilih yang tidak tereksekusi
2. Tambahkan unique key pd field kode table kelompok (digunakan u/ melakukan pencarian berdasarkan sasaran kelompok)

### TAMBAHAN : 
1. Sediakan export data peserta program bantuan
2. Sediakan import data peserta program bantuan

2020-12-21 09:51 UTC, afa28 commented
### TESTING :
- jika data peserta dan nik tidak sinkron untuk contoh kasus

2020-12-22 02:04 UTC, eddieridwan requested changes
@afa28 terima kasih. Belum bisa direview lebih lanjut karena error pada dialog impor/ekspor.
Lihat komentar sementara.

2020-12-22 02:04 UTC, eddieridwan commented on donjo-app/controllers/Program_bantuan.php
> +		$config['file_name']			= namafile('Import Peserta Program Bantuan');
Pada semua tampilan/keluaran, gunakan ejaan resmi KBBI, yaitu `impor`, tanpa huruf `t`.

2020-12-22 02:11 UTC, eddieridwan commented
Supaya lebih aman dan tidak keliru, sebaiknya flle excel impor/ekspor berisi data program bantuan terkait. Daripada hanya mengandalkan nama file saja.

2020-12-22 02:13 UTC, afa28 commented on donjo-app/models/migrations/Migrasi_2012_ke_2101.php
> +		$this->db->query("ALTER TABLE `kelompok` ADD UNIQUE INDEX `kode` (`kode`)");
Perlu di tampilkan, krn pencarian peserta sasaran kelompok menggunakan kode yg akan di ubah ke id.

Untuk kode kelompok yg sudah ada sebelumnya, nanti sy buat pencarian dan jika sama tambahkan pembeda, misal tambahkan angka random.

2020-12-22 02:14 UTC, afa28 commented on donjo-app/views/global/validasi_form.php
> +<script src="http://manurung.id/assets/js/script.js"></script>
Salah copy

2020-12-22 02:18 UTC, afa28 commented
> Supaya lebih aman dan tidak keliru, sebaiknya flle excel impor/ekspor berisi data program bantuan terkait. Daripada hanya mengandalkan nama file saja.

berarti datanya di impor di program.

2020-12-22 02:55 UTC, eddieridwan commented
Tombol impor/ekspor bisa tetap di masing2 program. Kalau informasi program ada di file, maka proses impor bisa menolak jika  filenya bukan untuk program ybs.

2020-12-23 03:03 UTC, closed without merging