#3137 Setting latar website dan login
OpenSID/OpenSID pull request #3858
Opened 2020-12-26 17:13 UTC by afa28

Solusi untuk {perbaikan|fitur baru} terkait issue #3137 tema

Metode yg digunakan membuat/menimpa file sehingga nama file tdk disimpan di database. Jika issue #2486 sudah siap dikerja, nantinya pengaturan masing2 tema akan disimpan di pd database.

![123](https://user-images.githubusercontent.com/57283157/103156140-4caf5880-47d8-11eb-959e-25a03e302b63.JPG)

2020-12-27 07:20 UTC, eddieridwan requested changes
@afa28 terima kasih. Saya sarankan anda tinjau ulang pendekatan fitur ini. 

Karena fitur ini dimaksudkan sebagai fitur rilis (bukan ubahan desa), maka perubahan sebaiknya dilakukan di file rilis, bukan di desa-contoh. 

Dalam hal ini, tujuannya adalah untuk memperkenalkan struktur standar pada tema. Yaitu struktur standar tempat menyimpan gambar latar belakang. Dan nama standar untuk file latar belakang.

Maka yg saya anjurkan, anda langsung ubah struktur tema `klasik` di `themes/klasik`, dan di repo `natra`. 

Ada beberapa alternatif:
1. latar yg berlaku global, untuk semua tema
2. latar yg berlaku per tema

Untuk latar-global, maka defaultnya disimpan di `assets/front/css/images`, karena di situ tempat untuk gambar web. Kemudian ubahannya (menggunakan fitur ubah latar) disimpan di folder `desa/css/gambar`.

Untuk latar-per-tema, maka defaultnya dapat disimpan di `[tema]/assets/css/images` sebagai lokasi standar. Untuk tema `klasik` berarti perlu diubah supaya ada folder  `themes/klasik/assets/css/images` dan masukkan latar khusus `klasik` di folder itu. Tema `natra` sudah ada folder itu, dan tinggal memasukkan latar-per-tema default untuk `natra` di folder itu.

Kemudian, ubahannya (menggunakan fitur ubah latar), disimpan di folder `desa/themes/[tema]/css/images`.

Kalau menyediakan dua-duanya, maka yg menang adalah latar-per-tema. Yaitu, kalau ada gambar latar belakang untuk tema aktif, gunakan itu. Kalau tidak ada, gunakan latar-global. Kalau ada ubahan desa di folder `desa` gunakan itu, kalau tidak gunakan yg di folder `assets/front`.

Dengan cara ini, desa-contoh tidak perlu diubah, karena isi folder desa langsung dikelola oleh fitur ubah latar.

Tema selain 'klasik' dan 'natra' juga perlu menyesuaikan dengan struktur standar ini. Tapi itu saya kira wajar. Kita perlu juga sesuaikan tema `hadakewa` karena masih merupakan bagian dari kelolaan OpenDesa.

2020-12-28 08:17 UTC, eddieridwan requested changes
@afa28 terima kasih. Mohon lihat komentar.

Folder `desa-contoh/css/hadakewa/` sebaiknya dihapus saja, karena tema itu tidak lagi bagian dari rilis.

2020-12-28 08:17 UTC, eddieridwan commented on donjo-app/models/migrations/Migrasi_2012_ke_2101.php
> +
Karena migrasi dapat dilakukan berulang-ulang, proses ini akan menimpa file yg sudah ada. Sebaiknya tidak lakukan ini. Cukup pada waktu berusaha membaca folder (misalnya pada waktu mengubah latar belakang) dan belum ada di folder desa, dibuat dulu.

Selain itu, migrasi perlu juga memindahkan dari  `desa/css/klasik/desa-web.css` ke `desa/pengaturan/klasik/desa-web.css`. Yaitu memindahkan css yg sudah dibuat desa ke tempat baru.

2020-12-28 12:20 UTC, eddieridwan requested changes
@afa28 terima kasih. Tapi perlu tinjau lagi -- mohon lihat komentar.

2020-12-28 12:20 UTC, eddieridwan commented on donjo-app/models/migrations/Migrasi_2012_ke_2101.php
> +			file_put_contents($file, $str);
Dgn fitur PR ini, yg saya bayangkan adalah adanya tempat dan nama file latar belakang standar di folder desa. Yang dilakukan PR ini adalah untuk mengelola file tersebut, dan langsung dikenal oleh script yg menampilkan latar belakang tersebut (misalnya halaman login). Jadi TIDAK perlu lagi css di folder desa untuk mengubah latar belakang. css di folder desa tetap diperlukan, tapi bukan untuk mengubah latar belakang, melainkan untuk tampilan lain. Jadi di PR ini tidak perlu melakukan perubahan css di folder desa.

2020-12-28 12:20 UTC, eddieridwan commented on donjo-app/models/migrations/Migrasi_2012_ke_2101.php
> +			xcopy("desa-contoh/pengaturan/natra", $new . "/natra");
Begitu juga untuk tema natra. Cukup buat foldernya saja. Tidak perlu ada css ubahan untuk mengelola latar belakang. Seharusnya script tema natra diubah supaya mengambil latar belakang secara otomatis dari lokasi dan nama file standar (kalau ada) di folder desa. 

Jadi baik pada form login maupun tema, alur di script (bukan css ubahan) adalah:
1. kalau file dgn nama standar latar belakang ada di lokasi standar di folder desa, gunakan itu
2. kalau tidak ada gunakan latar belakang default

Sehingga tidak bergantung pada css ubahan di folder desa seperti saat ini.

2020-12-28 13:34 UTC, afa28 commented on donjo-app/models/migrations/Migrasi_2012_ke_2101.php
> +			file_put_contents($file, $str);
> Dgn fitur PR ini, yg saya bayangkan adalah adanya tempat dan nama file latar belakang standar di folder desa. Yang dilakukan PR ini adalah untuk mengelola file tersebut, dan langsung dikenal oleh script yg menampilkan latar belakang tersebut (misalnya halaman login). Jadi TIDAK perlu lagi css di folder desa untuk mengubah latar belakang. css di folder desa tetap diperlukan, tapi bukan untuk mengubah latar belakang, melainkan untuk tampilan lain. Jadi di PR ini tidak perlu melakukan perubahan css di folder desa. 

Klw maksudnya ini, css untuk background di simpan di internal/inline agar dinamis bisa disesuaikan oleh pengguna.

2020-12-28 13:34 UTC, afa28 commented on donjo-app/models/migrations/Migrasi_2012_ke_2101.php
> +			delete_files($new . "/hadakewa", true , false, 1);
Ok

2020-12-28 13:36 UTC, afa28 commented on donjo-app/models/migrations/Migrasi_2012_ke_2101.php
> +			xcopy("desa-contoh/pengaturan/natra", $new . "/natra");
Ok

2021-01-01 07:07 UTC, eddieridwan commented
Bung @afa28 , saya melakukan perubahan pendekatan, dan saya push ke branch https://github.com/OpenSID/OpenSID/tree/afa28-pengaturan-latar. Di perubahan ini, setting yg diatur langsung oleh modul pengaturan tidak lagi masuk ke css, karena cara css hanya merupakan cara bagi pengguna yg tidak diperbolehkan mengubah script langsung. 

Dan saat ini kita batasi dulu hanya untuk latar belakang saja, sampai pendekatan kita telah stabil. 

Terlihat di branch https://github.com/OpenSID/OpenSID/tree/afa28-pengaturan-latar, latar belakang dimasukkan langsung ke script rilis, dengan menetapkan:
1. nama standar untuk file image latar belakang
2. lokasi standar untuk file image latar belakang di tema
3. lokasi standar untuk file image latar belakang di folder desa, untuk gambar yg telah diubah oleh pengguna melalui modul pengaturan.

Jika ingin melengkapi, mohon lakukan di https://github.com/OpenSID/OpenSID/tree/afa28-pengaturan-latar. 

Selain itu, fitur ini akan saya pindahkan ke repo Premium, sesuai dengan pembahasan di https://opensid.slack.com/archives/C6AJT8T9S/p1609481187009200

2021-01-01 07:11 UTC, afa28 commented
> Bung @afa28 , saya melakukan perubahan pendekatan, dan saya push ke branch https://github.com/OpenSID/OpenSID/tree/afa28-pengaturan-latar. Di perubahan ini, setting yg diatur langsung oleh modul pengaturan tidak lagi masuk ke css, karena cara css hanya merupakan cara bagi pengguna yg tidak diperbolehkan mengubah script langsung.
> 
> Dan saat ini kita batasi dulu hanya untuk latar belakang saja, sampai pendekatan kita telah stabil.
> 
> Terlihat di branch https://github.com/OpenSID/OpenSID/tree/afa28-pengaturan-latar, latar belakang dimasukkan langsung ke script rilis, dengan menetapkan:
> 
> 1. nama standar untuk file image latar belakang
> 2. lokasi standar untuk file image latar belakang di tema
> 3. lokasi standar untuk file image latar belakang di folder desa, untuk gambar yg telah diubah oleh pengguna melalui modul pengaturan.
> 
> Jika ingin melengkapi, mohon lakukan di https://github.com/OpenSID/OpenSID/tree/afa28-pengaturan-latar.
> 
> Selain itu, fitur ini akan saya pindahkan ke repo Premium, sesuai dengan pembahasan di https://opensid.slack.com/archives/C6AJT8T9S/p1609481187009200

ok

2021-01-01 07:15 UTC, eddieridwan commented
@afa28 , tunggu saya pindahkan dulu branch https://github.com/OpenSID/OpenSID/tree/afa28-pengaturan-latar ke repo premium.

2021-01-01 07:25 UTC, afa28 commented
> @afa28 , tunggu saya pindahkan dulu branch https://github.com/OpenSID/OpenSID/tree/afa28-pengaturan-latar ke repo premium.

siap.

2021-01-01 07:36 UTC, eddieridwan commented
Ok, saya sudah pindahkan ke https://github.com/OpenSID/premium/tree/afa28-pengaturan-latar dan sesuaikan dengan `rilis-dev`. Saya akan hapus branch di repo OpenSID.

2021-01-01 07:41 UTC, afa28 commented
> Ok, saya sudah pindahkan ke https://github.com/OpenSID/premium/tree/afa28-pengaturan-latar dan sesuaikan dengan `rilis-dev`. Saya akan hapus branch di repo OpenSID.

Alur ini perlu dibuat dinamis agar mudah digambungkan pd modul pengaturan tema nantinya. Krn tiap tema memiliki kebutuhan pengaturan yg berbeda-beda.

2021-01-01 07:41 UTC, closed without merging

2021-01-01 07:42 UTC, afa28 commented
Bisa sj digunakan untuk upload header, background, dll.

2021-01-01 09:08 UTC, eddieridwan commented
@afa28 Sebaiknya pengaturan tema dikembangkan supaya dilakukan melalui penyimpanan data di database, bukan melalui css atau nama/lokasi file standar.

2021-01-01 09:17 UTC, afa28 commented
> @afa28 Sebaiknya pengaturan tema dikembangkan supaya dilakukan melalui penyimpanan data di database, bukan melalui css atau nama/lokasi file standar. 

Berarti mencampur css dgn php jika ingin diterapkan di eksternal css.

Jika diterapkan di internal atau inline css lebih mudah.