Revisi
OpenSID/OpenSID pull request #3860
Opened 2020-12-27 14:48 UTC by nopezi

Solusi untuk {perbaikan|fitur baru} terkait issue {#1, #2, #3, dst.}

2020-12-28 10:40 UTC, eddieridwan requested changes
@nopezi terima kasih. Lihat komentar.

2020-12-28 10:40 UTC, eddieridwan commented on donjo-app/controllers/Web.php
> +
Conflict perlu diresolve dulu

2020-12-28 10:40 UTC, eddieridwan commented on donjo-app/helpers/opensid_helper.php
> +=======
Conflict perlu diresolve dulu.

2020-12-29 02:07 UTC, nopezi commented on donjo-app/controllers/Web.php
> +
sudah di hilangkan

2021-01-11 06:37 UTC, eddieridwan commented
Bung @nopezi apakah PR ini sudah siap direview ulang?

2021-06-17 06:10 UTC, afa28 commented
Pak @nopezi silahkan perbaharui PR ini.

2021-09-26 11:55 UTC, closed without merging