#3069 : Pencarian spesifik keluarga
OpenSID/OpenSID pull request #3862
Opened 2020-12-28 05:42 UTC by afa28

Solusi untuk {perbaikan|fitur baru} terkait issue #3069

TODO : 
1. Tambahkan pencarian spesifik keluarga lainnya

2020-12-28 11:43 UTC, eddieridwan requested changes
@afa28 terima kasih. Tapi pencarian spesifik keluarga gagal menampilkan peserta program bantuan. Dan pencarian spesifik penduduk gagal untuk pencarian selain program bantuan.

2020-12-28 13:43 UTC, afa28 commented
> @afa28 terima kasih. Tapi pencarian spesifik keluarga gagal menampilkan peserta program bantuan. Dan pencarian spesifik penduduk gagal untuk pencarian selain program bantuan.

Pencarian program bantuan yg sebelumnya sy gabung dgn pencarian spesifik, sekrang sudah sy pisahkan untuk pencarian program bantuan.

2021-01-01 11:47 UTC, eddieridwan requested changes
@afa28 terima kasih.

Ikuti langkah berikut:
1. buka pencarian spesifik penduduk
2. isi pencarian, misalnya jenis pekerjaan, dan klik simpan
3. buka lagi pencarian spesifik penduduk
4. perhatikan kolom yg diisi sebelumnya, misalnya jenis pekerjaan

Kolom itu kosong -- seharusnya menampilkan isian sebelumnya.

2021-01-01 12:03 UTC, afa28 commented
Sudah sy kembalikan seperti semula, krn pencarian program bantuan sudah tdk dimasukkan di pencarian spesifik (dipisah)

2021-01-02 09:03 UTC, eddieridwan commented
@afa28 terima kasih. Sdh digabung ke `rilis-dev`

2021-01-02 09:03 UTC, closed without merging

2021-01-02 09:07 UTC, eddieridwan commented
Perhatikan bahwa issue #3069 nilai tambahnya relatif kecil, karena fitur serupa tersedia di Statistik > Statistik Kependuduk. Bahkan di menu statistik juga bisa menampilkan penduduk/keluarga yg belum menerima bantuan. Karena itu, sebenarnya 
#3069 prioritasnya relatif rendah.

2021-01-02 09:49 UTC, afa28 commented
> Perhatikan bahwa issue #3069 nilai tambahnya relatif kecil, karena fitur serupa tersedia di Statistik > Statistik Kependuduk. Bahkan di menu statistik juga bisa menampilkan penduduk/keluarga yg belum menerima bantuan. Karena itu, sebenarnya 
> #3069 prioritasnya relatif rendah.

Yah, tdk masalah. Masalah poin atau lainnya, diserahkan ke pak @eddieridwan sj. Sy cuma bantu selesaikan issue yg ada.

2021-01-02 10:45 UTC, eddieridwan commented
@afa28 bukan masalah poin. Maksud 'nilai tambah' lebih ke prioritas (atau manfaat) yg dirasakan teman2 pemangku kepentingan, seperti bung Mizwaruddin, Rarang Selatan, dll. Yaitu, yg mana yg didahulukan... itu saja... tetapi tentunya teman2 programmer bebas mengerjakan sesukanya. Teruskan!

2021-01-02 10:46 UTC, afa28 commented
> @afa28 bukan masalah poin. Maksud 'nilai tambah' lebih ke prioritas (atau manfaat) yg dirasakan teman2 pemangku kepentingan, seperti bung Mizwaruddin, Rarang Selatan, dll. Yaitu, yg mana yg didahulukan... itu saja... tetapi tentunya teman2 programmer bebas mengerjakan sesukanya. Teruskan!

Ok, siap pak.