Menyesuaikan Tampilan Web Baru
OpenSID/OpenSID pull request #3864
Opened 2020-12-29 03:43 UTC by ariandii

Ganti Tampilan Website pada Halaman Readme

2021-01-01 11:54 UTC, eddieridwan requested changes
@ariandii , sepertinya PR ini berisi perubahan dari proses rilis?

Issue mana yg dikerjakan oleh PR ini? Mohon disesuaikan dan kirim ulang.

2021-01-02 04:56 UTC, balongbesuk commented
![pendopo](https://user-images.githubusercontent.com/35319600/103451040-71806000-4cf1-11eb-8f84-fb00e0203b8b.jpg)

2021-01-02 04:57 UTC, balongbesuk commented
![received_1236399309819917](https://user-images.githubusercontent.com/35319600/103451051-a68cb280-4cf1-11eb-95e5-1676a001dcfa.jpg)

2021-01-04 10:02 UTC, eddieridwan commented
@ariandii terima kasih. Saya gabungkan perubahan gambar readme secara manual, karena PR anda berisi commit tidak terkait.

2021-01-04 10:02 UTC, closed without merging