Issue 3992 clean
OpenSID/OpenSID pull request #3993
Opened 2021-02-07 15:32 UTC by satiri

solusi untuk issue #3992 
- mencopy script.js dan menghapus fungsi2 yang membutuhkan library yang tidak diload di halaman web/mandiri
- mengubah const menjadi var karena variable akan di override oleh corona-widget.php

2021-02-08 07:02 UTC, eddieridwan requested changes
@satiri terima kasih. 

Solusi ini mengakibatkan duplikasi di `assets/js/script-web.js` dan `assets/js/script.js` yg tentunya tidak ideal.

Alternatif lain adalah mengeluarkan js terkait select2 dari `assets/js/script.js` ke file terpisah, misalnya `assets/js/select.js`. Sehingga bisa dipasang hanya jika menggunakan select2.

2021-02-09 02:52 UTC, satiri commented
Terimakasih, Baik Pak. Akan saya balik PR nya menjadi file yang tidak di
load di web

2021-02-09 12:13 UTC, satiri commented
PR updated

2021-02-09 12:24 UTC, afa28 commented on donjo-app/views/global/validasi_form.php
> +<?php IF($_SESSION['UI'] === 'ADMIN'): ?>
Bisa pakai session dari siteman = 1 (admin login) dr pd buat session baru.

2021-02-10 01:55 UTC, eddieridwan commented
@satiri , apakah PR ini sudah siap direvew ulang? Kalau sudah siap, klik saja tombol Re-request Review.

2021-02-13 05:48 UTC, satiri commented
ok pak.

Pada tanggal Rab, 10 Feb 2021 pukul 08.55 Eddie Ridwan <
notifications@github.com> menulis:

> @satiri <https://github.com/satiri> , apakah PR ini sudah siap direvew
> ulang? Kalau sudah siap, klik saja tombol Re-request Review.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenSID/OpenSID/pull/3993#issuecomment-776374939>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAID6J34JYOCLDWAYWGIG6LS6HRSPANCNFSM4XHRZD3Q>
> .
>

2021-02-16 05:53 UTC, eddieridwan commented
@satiri terima kasih. Solusi anda tidak bisa digunakan secara utuh, karena masih menggunakan cara duplikasi. Tetapi sebagian unsur script anda digunakan di solusi yg telah digabung ke `rilis-dev`.

Solusi yg digabung terdiri dari dua cara:
1. Memecah kumpulan script terkait yg relatif besar ke file tersendiri. Yaitu script `select2` dipindah dari `script.js` ke `assets/js/custom-select2.js, dan script `datetimepicker` dipindah ke file `assets/js/custom-datetimepicker.js`
2. Bagi script yg hanya ada satu-dua baris, diperiksa dulu apakah elemen terkait ada atau tidak, sbb:
```
  //color picker with addon
  if ($('.my-colorpicker2').length > 0) $('.my-colorpicker2').colorpicker();
  //Text Editor with addon
  if ($('#min-textarea').length > 0) $('#min-textarea').wysihtml5();
```
Issue https://github.com/OpenSID/OpenSID/issues/3992 belum ditutup, karena masih ada error console tema natra yg tidak terkait `script.js`.

2021-02-16 05:53 UTC, closed without merging

2021-02-16 05:56 UTC, eddieridwan commented on donjo-app/views/global/validasi_form.php
> +<?php IF($_SESSION['UI'] === 'ADMIN'): ?>
Cara ini tidak bisa digunakan, karena jika admin telah login, dan kemudian membuka web, tetap terdeteksi bahwa admin telah login.

2021-02-16 06:26 UTC, satiri commented
trims pak Eddie, tujuan saya sebenarnya untuk mengelompokan halaman.
bukan untuk melihat siapa yang login.


Pada tanggal Sel, 16 Feb 2021 pukul 12.56 Eddie Ridwan <
notifications@github.com> menulis:

> *@eddieridwan* commented on this pull request.
> ------------------------------
>
> In donjo-app/views/global/validasi_form.php
> <https://github.com/OpenSID/OpenSID/pull/3993#discussion_r576565585>:
>
> >  <script src="<?= base_url('assets/js/script.js'); ?>"></script>
> +
> +<?php IF($_SESSION['UI'] === 'ADMIN'): ?>
>
> Cara ini tidak bisa digunakan, karena jika admin telah login, dan kemudian
> membuka web, tetap terdeteksi bahwa admin telah login.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenSID/OpenSID/pull/3993#discussion_r576565585>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAID6J6OJVHHGCVNEV4HI6TS7ICIRANCNFSM4XHRZD3Q>
> .
>

2021-02-16 06:42 UTC, eddieridwan commented
@satiri , solusi yg diterapkan mengirim parameter secara eksplisit ke `global/validasi_form`, supaya tidak harus menebak atau membuat algoritma yg rumit atau menambah session variable.

Jadi tema natra memanggil sebagai berikut:
`<?php $this->load->view('global/validasi_form', ['web_ui' => true]); ?>
`

2021-02-16 07:35 UTC, satiri commented
Trims pak.

Pada tanggal Sel, 16 Feb 2021 pukul 13.42 Eddie Ridwan <
notifications@github.com> menulis:

> @satiri <https://github.com/satiri> , solusi yg diterapkan mengirim
> parameter secara eksplisit ke global/validasi_form, supaya tidak harus
> menebak atau membuat algoritma yg rumit atau menambah session variable.
>
> Jadi tema natra memanggil sebagai berikut:
> <?php $this->load->view('global/validasi_form', ['web_ui' => true]); ?>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenSID/OpenSID/pull/3993#issuecomment-779623077>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAID6J7SWQ2HBDSW2RB77S3S7IHVJANCNFSM4XHRZD3Q>
> .
>