Layanan mandiri auth
OpenSID/OpenSID pull request #4067
Opened 2021-03-17 06:33 UTC by afa28

Solusi untuk perbaikan terkait issue #4047

Catatan : Layanan Mandiri Versi Lama tidak di kembangkan lagi, hanya akn dilakukan perbaiki jika ada bugs sampai Layanan Mandiri Versi Terbaru digabungkan dengan rilis umum.

2021-03-19 02:09 UTC, eddieridwan requested changes
@afa28 terima kasih. 

Apakah solusi anda menggunakan cara yg persis sama seperti yg ada di  v20.12-premium (atau sejauh mungkin mendekati)?

Karena rilis premium berikutnya yg akan digabungkan ke `master` adalah v20.12-premium. Untuk menghindari pusing seribu keliling karena banyak sekali conflict, perubahan di `master` harus mendekati solusi di v20.12-premium.

2021-03-19 02:16 UTC, afa28 commented
> @afa28 terima kasih. 
> 
> Apakah solusi anda menggunakan cara yg persis sama seperti yg ada di  v20.12-premium (atau sejauh mungkin mendekati)?
> 
> Karena rilis premium berikutnya yg akan digabungkan ke `master` adalah v20.12-premium. Untuk menghindari pusing seribu keliling karena banyak sekali conflict, perubahan di `master` harus mendekati solusi di v20.12-premium.
> 

Ini hanya memisahkan mandiri_web (tambahkan cek login) dan mandiri_login untuk auth untuk menutupi akses langsung ke layanan mandiri.

Jika rilis layanan mandiri premium akan digabungkan dgn versi umum, PR ini tdk diperlukan lg. Krn ini hanya bug sj, tdk ad pengecekan saat login.

2021-03-19 02:19 UTC, eddieridwan commented
@afa28 Bug yg menyebabkan fitur tidak dapat digunakan perlu diperbaiki. Tetapi error yg tidak berakibat fatal dan tidak mempengaruhi keamanan data, tidak perlu diperbaiki. 

Jadwal penggabungan rilis premium ke rilis umum dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang

2021-03-19 02:49 UTC, afa28 commented
Yg bisa dilakukan tampa login mandiri yakni mengunduh dokumen penduduk dengan menlakukan kombinasi perulangan id_dokumen dan id_penduduk.

Contoh:
id_penduduk = 1 dan id_dokumen = n.

https://demo.opensid.or.id/mandiri_web/unduh_berkas/1/1
https://demo.opensid.or.id/mandiri_web/unduh_berkas/2/1
https://demo.opensid.or.id/mandiri_web/unduh_berkas/3/1
https://demo.opensid.or.id/mandiri_web/unduh_berkas/4/1
https://demo.opensid.or.id/mandiri_web/unduh_berkas/5/1
https://demo.opensid.or.id/mandiri_web/unduh_berkas/6/1
https://demo.opensid.or.id/mandiri_web/unduh_berkas/7/1
https://demo.opensid.or.id/mandiri_web/unduh_berkas/n/1

dan yg sy temukan
https://demo.opensid.or.id/mandiri_web/unduh_berkas/30/1
https://demo.opensid.or.id/mandiri_web/unduh_berkas/31/1

2021-03-19 03:09 UTC, eddieridwan commented
@afa28 berarti masalah yg perlu diperbaiki. Tapi perbaikan perlu konsisten dengan script yg di v20.12-premium, atau yg ada di v21.02 (yaitu versi rilis umum sebelumnya) -- tergantung mana yg lebih cocok.

2021-03-19 03:14 UTC, afa28 commented
> @afa28 berarti masalah yg perlu diperbaiki. Tapi perbaikan perlu konsisten dengan script yg di v20.12-premium, atau yg ada di v21.02 (yaitu versi rilis umum sebelumnya) -- tergantung mana yg lebih cocok. 
 
Klau versi premium masalah ini sudah diperbaiki. 

Pada versi umum merupakan script bawaan yg lama, jd cukup ditambal saja untuk sementara waktu. Krn ketika layanan mandiri versi premium digabung, versi lamanya banyak yg dihapus.

2021-03-19 03:20 UTC, eddieridwan commented
> Jd sy buat strukturnya mirip2 dgn versi terbaru tanpa menambahkan fitur lainnya.

Jangan dengan versi terbaru, tetapi mirip v20.12-premium. Kalau mirip dengan v21.03-premium justru akan menimbulkan masalah conflict yg banyak pada waktu menggabungkan v20.12-premium ke `master`.

2021-03-19 03:25 UTC, afa28 commented
> > Jd sy buat strukturnya mirip2 dgn versi terbaru tanpa menambahkan fitur lainnya.
> 
> Jangan mirip versi terbaru, tetapi mirip v20.12-premium. Kalau mirip dengan v21.03-premium justru akan menimbulkan masalah conflict yg banyak pada waktu menggabungkan v20.12-premium ke `master`.

Alurnya yg sy buat sesuai dgn versi premium. Untuk conflic hanya akan terjadi pd core/clas layanan_mandiri, js dan css layanan mandiri lama akan diganti semua dgn yg baru, selebihnya controller layanan mandiri versi lama akan dihapus menggantikan versi terbaru (yg disimpan di folder khusus layanan_mandiri) saat di merge.

2021-03-19 03:28 UTC, eddieridwan commented
@afa28 coba periksa v20.11-premium. Yg ada di `master` adalah hasil penggabungan v20.11-premium. Di situ, masalah ini seharusnya tidak ada. Jadi yg terjadi sepertinya ada yg kurang pada waktu melakukan conflict resolution. Jadi mohon samakan dengan solusi yg ada di v20.11-premium.

2021-03-19 03:30 UTC, afa28 commented
> @afa28 coba periksa v20.11-premium. Yg ada di `master` adalah hasil penggabungan v20.11-premium. Di situ, masalah ini seharusnya tidak ada. Jadi yg terjadi sepertinya ada yg kurang pada waktu melakukan conflict resolution waktu menggabungkan v20.11-premium ke `master`. Jadi mohon samakan dengan solusi yg ada di v20.11-premium.
> 

Ok, sy cek ulang habis jumat.

2021-03-19 07:42 UTC, afa28 commented
> @afa28 coba periksa v20.11-premium. Yg ada di `master` adalah hasil penggabungan v20.11-premium. Di situ, masalah ini seharusnya tidak ada. Jadi yg terjadi sepertinya ada yg kurang pada waktu melakukan conflict resolution waktu menggabungkan v20.11-premium ke `master`. Jadi mohon samakan dengan solusi yg ada di v20.11-premium.

Sudah sy cek, pada v20.11-premium tdk dilakukan perbaikan pengecekan login pd controller layanan mandiri. Ini diperbaiki pada  v21.01-premium dengan memisahkan mandiri_login dan mandiri_web. https://github.com/OpenSID/premium/tree/v21.01-premium/donjo-app/controllers. Dan dirombak secara keseluruhan pada v21.03-premium.

2021-03-19 08:40 UTC, eddieridwan commented
Apakah masalah yg dilaporkan ditemukan di v20.11-premium?

2021-03-19 08:43 UTC, afa28 commented
> Apakah masalah yg dilaporkan ditemukan di v20.11-premium?

Tidak pak @eddieridwan, yg dilaporkan versi rilis umum  yg merupakan layanan mandiri versi awal. https://github.com/OpenSID/OpenSID/issues/4047

2021-03-19 08:45 UTC, eddieridwan commented
@afa28  Kalau di v20.11-premium aman, gunakan cara itu di rilis umum, karena memang versi itu yg digabungkan.

2021-03-19 08:49 UTC, afa28 commented
Yg bisa dilakukan : 
1. Membiarkan bug tsb pd rilis umum tp keamanan data penduduk desa bakal terancam.
2. Menpercepat v21.01-premium digabung ke rilis umum.
3. Menambal sementara bug tsb (PR https://github.com/OpenSID/OpenSID/pull/4067), nanti disesuaikan lg setelah digabungkan dr v21.01-premium.

2021-03-19 08:56 UTC, afa28 commented
> @afa28  Kalau di v20.11-premium aman, gunakan cara itu di rilis umum, karena memang versi itu yg digabungkan. 

Ok.

2021-03-19 09:31 UTC, afa28 commented
Sudah sy sesuaikan layanan mandiri mengikuti v21.01-premium pak @eddieridwan, hanya mengambil bagian2 yg perlu sj untuk pengecekan login.

2021-03-19 18:47 UTC, ndunks commented
Jika di versi premium sudah di patch, maka tinggal merge via 'patch' aja secara spesifik pada commit yg isinya memperbaiki bug tersebut. atau bisa make metode [rebase](https://stackoverflow.com/questions/7744049/git-how-to-rebase-to-a-specific-commit)

2021-03-23 08:56 UTC, afa28 commented
> > Sudah sy sesuaikan layanan mandiri mengikuti v21.01-premium pak @eddieridwan, hanya mengambil bagian2 yg perlu sj untuk pengecekan login.
> 
> Seharusnya bukan mengambil dari v21.01-premium, tetapi dari `v20.11-premium` (kalau versi itu aman). Mohon ambil dari versi yg lama itu. Karena itu yg digabung ke v21.03. 
> 
> Sekali lagi: Apakah v20.11-premium aman? Kalau iya, gunakan cara yg di v20.11-premium, karena versi itu yg digabung ke v21.03. Karena kalau bermasalah di v21.03, itu karena ada yg terlewat pada waktu conflict resolution. 
> 
> Perhatikan, bahwa penggabanguan ke rilis umum berikut adalah dari v20.12-premium (bukan dari v21.01-premium). Jadi kalau anda mengambil dari v21.01-premium, akan menyebabkan masalah conflict resolution yg lebih repot pada waktu menggabungkan v20.11-premium ke v21.07.
> 
> v20.11-premium --> v21.03 (yg sekarang)
> v20.12-premium --> v21.07 (penggabungan berikutnya)

Yg aman v21.01-premium pak @eddieridwan , yg v20.11-premium masih menggunakan cara lama (tdk ad pengecekan user login).

Artinya, kita menunggu sj sampai v21.01-premium digabungkan dan dibiarkan seperti itu.

2021-03-23 09:09 UTC, closed without merging