Add laporan surat
OpenSID/OpenSID pull request #4070
Opened 2021-03-19 18:42 UTC by ndunks

Menambahkan sub menu statistik untuk menampilkan laporan surat bulanan.

![image](https://user-images.githubusercontent.com/5500313/111828176-7d0d1b80-891d-11eb-8d7d-0999b07f77c5.png)

2021-03-19 18:43 UTC, ndunks commented
Close aja bang misal ndak kepake, cuman mau share aja..

2021-03-21 00:33 UTC, eddieridwan commented
@ndunks terima kasih. Ada beberapa hal.

1. Untuk setiap PR, perlu ada issue terkait. Di issue itu dijelaskan apa fitur yg diinginkan. Issue itu yg digunakan untuk melakukan review setiap PR. Bisa lihat penjelasan di https://github.com/OpenSID/OpenSID/wiki/Proses-Review-Pull-Request
2. Untuk mengubah struktur data, tidak mengubah contoh data awal. Tetapi membuat migrasi seperti dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Menambah-Migrasi-Database
3. Sebelum menambah helper, seperti `opensid_nama_bulan()` periksa dulu apakah sdh ada. Lihat helper serupa di `donjo-app/helpers/donjolib_helper.php`.

Kalau anda buat issuenya, atau bahas di https://www.facebook.com/groups/OpenSID, teman2 yg lain bisa memberi masukan. Kemungkinan besar mereka akan mengatakan bahwa untuk menghasilkan laporan surat bulanan, anda tinggal tambahkan filter bulan di `Layanan Surat > Arsip Layanan`. 

Silakan anda buatkan issue dan buat ulang PR anda sesuai dengan komentar di atas. Terima kasih. 

![surat-bulanan](https://user-images.githubusercontent.com/249563/111889870-8a6af880-8a38-11eb-80a6-c7ddfebe2164.jpg)

2021-03-21 00:34 UTC, eddieridwan requested changes
@ndunks terima kasih. Lihat komentar.

2021-04-06 06:06 UTC, eddieridwan commented
@ndunks , sudah ditambahkan filter `bulan` di Arsip Layanan Surat. Bisa diperiksa di https://berputar.opensid.or.id. Kalau ada yg kurang, silakan buat issue terpisah. PR ini akan ditutup, karena fiturnya sudah diterapkan Terima kasih.

![filter-bulan](https://user-images.githubusercontent.com/249563/113666075-fb293a80-96f1-11eb-8961-fd1d1d2e8546.jpg)

2021-04-06 06:06 UTC, closed without merging