evaluasi SDGs Kemendesa di web OpenSID
OpenSID/OpenSID pull request #4132
Opened 2021-04-09 15:07 UTC by apidong

Solusi untuk {perbaikan|fitur baru} terkait issue {#4121}

2021-04-09 15:14 UTC, apidong reviewed
men-scraping halaman SDGs kemendesa yang pada halaman sid.kemendesa.go.id/home/sdgs/{$kode_desa}

2021-04-11 02:16 UTC, eddieridwan requested changes
@apidong terima kasih. Diperlukan beberapa perbaikan. Tapi mohon anda pindahkan PR anda ke repo https://github.com/OpenSID/premium. Fitur baru dikembangkan di repo itu dan tidak lagi di repo https://github.com/OpenSID/OpenSID.

Anda sudah di-invite untuk mendapat akses ke https://github.com/OpenSID/premium, supaya anda bisa buat fork dan kirim PR ke repo itu. 

Buat PR anda menggunakan branch `rilis-dev` di https://github.com/OpenSID/premium/tree/rilis-dev.

2021-04-11 02:24 UTC, eddieridwan commented on donjo-app/models/Data_eksternal_model.php
> +/* End of file Sdgs_model.php */
Komentar perlu disesuaikan dengan nama file.

2021-04-11 02:25 UTC, eddieridwan commented on donjo-app/models/Data_eksternal_model.php
> +/* End of file Sdgs_model.php */
Tambahkan blok lisensi di awal file. Lihat contoh di file lain.

2021-04-11 02:32 UTC, eddieridwan commented on themes/klasik/partials/kemendes_sdgs.php
> +  </div>
@apidong mohon ubah semua file yg anda tambahkan supaya indentasinya sesuai aturan penulisan script di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script. Yaitu indentasi menggunakan `tab` bukan spasi, dengan jarak 2 karakter.

2021-04-20 00:07 UTC, eddieridwan commented
PR ini ditutup, karena sdh dipindah ke https://github.com/OpenSID/premium/pull/189

2021-04-20 00:07 UTC, closed without merging