Gabung rilis opensid-premium v21.01
OpenSID/OpenSID pull request #4329
Opened 2021-07-15 16:53 UTC by agungsugiarto

2021-07-17 04:49 UTC, agungsugiarto commented on donjo-app/controllers/Mandiri_web.php
> +	public function update_pin($nik = '')
Mandiri model branch master, masih ada parameter nik ?

Model: https://github.com/OpenSID/OpenSID/blob/3cb044536c76f885991588f38a95d01a7421784d/donjo-app/models/Mandiri_model.php#L368

2021-07-17 08:00 UTC, afa28 commented on donjo-app/controllers/Mandiri_web.php
> +	public function update_pin($nik = '')
sudah dihilangkan di versi 21.04, https://github.com/OpenSID/OpenSID/blob/v21.04/donjo-app/controllers/Mandiri_web.php

2021-07-17 08:25 UTC, afa28 commented on donjo-app/core/MY_Controller.php
>  		$this->header = $this->config_model->get_data();;
Ini kyakanya double dgn `$this->header = $this->header_model->get_data();`

2021-07-17 08:25 UTC, afa28 commented on donjo-app/views/pelanggan/form.php
> +					<div id="error_msg" class="alert alert-danger" style="display: none;">
Kayaknya file ini sudah dhapus digantikan dengan yg baru dirilis sebelumnya???

2021-07-22 02:41 UTC, agungsugiarto commented
Pak @eddieridwan, pr ini sudah siap di merge mohon untuk di review akhir.

2021-07-23 05:30 UTC, eddieridwan requested changes
@agungsugiarto terima kasih. Sepertinya sdh ok.

Perlu mutakhirkan catatan rilis (v21.07-pasca gabungkan v21.01-premium). Dan ganti menjadi versi v21.07-pasca di opensid_helper.php sebelum digabung ke `master`.

2021-07-23 05:47 UTC, agungsugiarto commented
> @agungsugiarto terima kasih. Sepertinya sdh ok.
> 
> Perlu mutakhirkan catatan rilis (v21.07-pasca gabungkan v21.01-premium). Dan ganti menjadi versi v21.07-pasca di opensid_helper.php sebelum digabung ke `master`.

Saya rasa setelah digabungkan pak perubahan catatan rilis dan versi.

2021-07-23 05:53 UTC, eddieridwan commented
Sebelum digabungkan. Karena kalau sdh masuk `master` sdh bisa langsung diambil pengguna.

2021-07-23 09:01 UTC, agungsugiarto commented
Silahkan mas @afa28 untuk menggabungkan

2021-07-23 16:25 UTC, afa28 commented
> Silahkan mas @afa28 untuk menggabungkan

ok. sy cek ulang dlu.

2021-07-23 17:37 UTC, merged

2021-07-23 17:37 UTC, afa28 commented
Mas @agungsugiarto terima kasih. Sdh digabung ke `master` dengan perbaikan : 

1. Perbaharui tema natra agar menampilkan suplemen scr sempurna menggunakan https://github.com/OpenSID/tema-natra/tree/rilis-umum
2. Sesuaikan menjadi versi 21.08-pasca dan jalankan migrasi, agar bisa cek penambahan/perubahan fitur premium.

Catatan : 
1. contoh database awal sediakan di PR selanjutnya untuk rilis resmi.