new update Munculkan Pilihan Link Gallery pada saat membuat Menu Statis
OpenSID/OpenSID pull request #4537
Opened 2021-11-19 03:45 UTC by FirlianiF

Solusi untuk [Menu] Munculkan Pilihan Link Gallery pada saat membuat Menu Statis  terkait issue #3811.

2021-11-19 05:06 UTC, andifahruddinakas commented on donjo-app/config/routes.php
> +$route['sub_gallery/(:any)/(:num)'] = 'first/sub_gallery/$1/$2';
Buat jadi slug, ganti :
```
$route['sub_gallery'] = 'first/sub_gallery';
$route['sub_gallery/(:any)/(:num)'] = 'first/sub_gallery/$1/$2';
```

jadi

```
$route['sub-gallery'] = 'first/sub_gallery';
$route['sub-gallery/(:any)/(:num)'] = 'first/sub_gallery/$1/$2';
```

2021-11-19 05:06 UTC, andifahruddinakas commented on donjo-app/models/Referensi_model.php
> +	'sub_gallery' => 'Sub Gallery'
Ganti 
`'sub_gallery' => 'Sub Gallery'`
jadi
`'sub-gallery' => 'Sub Gallery'`

2021-11-19 09:36 UTC, andifahruddinakas commented
@FirlianiF, apakah sudah melakukan pengecekan hasil dari PR ini ???
1. Cek buat menu baru lewat admin.
2. Cek halaman (tema klasik) yang berkaitan dengan gallery.

2021-11-20 07:05 UTC, eddieridwan requested changes
@FirlianiF masih ada beberapa masalah. Untuk menemukan masalah, anda harus melakukan testing yg seksama.

1. Sekarang ternyata route `gallery` menjadi rancu, karena juga digunakan untuk membuka halaman gallery untuk admin. Sekarang menu admin `Admin Web > Galeri` salah, karena membuka halaman web. Jadi perlu menggunakan route yg berbeda untuk menampilkan gallery di web. Misalnya bisa menggunakan `web-gallery` untuk membedakan.

![galeri-1](https://user-images.githubusercontent.com/249563/142717566-fa386d05-1924-4364-8f67-918891bb2e75.jpg)

2. Pilihan sub-gallery tidak perlu ditampilkan di pilihan halaman statis. Cukup gallery saja, karena sub-gallery ditampilkan setelah membuka gallery.

3. Tautan yg tampil di menu statis untuk gallery masih ada prefix `first`.  Seharusnya tidak. Lihat contoh untuk tautan ke peta. Cari di script di mana untuk mencegah ditampilkannya `first` untuk halaman statis seperti peta, peraturan_desa dan gallery.

![galeri-2](https://user-images.githubusercontent.com/249563/142717693-1642cdb6-a9fc-4df2-a25e-54a5843d39c5.jpg)

4. Tampilan di tema natra salah, karena layout untuk halaman statis di tema natra berbeda. Untuk menyesuaikan ini pelajari contoh untuk halaman statis lainnya pada tema natra, seperti halaman peraturan_desa.

![galeri-3](https://user-images.githubusercontent.com/249563/142717811-29f6cedf-e67f-4513-9494-3269749723dd.jpg)
![galeri-4](https://user-images.githubusercontent.com/249563/142717814-b51951ba-8e50-4606-92c5-8e08df20b364.jpg)


Mohon diperbaiki. Dan lakukan testing secara seksama sebelum mengirim ulang.

Ditunggu. 

cc @andifahruddinakas

2021-11-20 12:53 UTC, eddieridwan requested changes
Ternyata sdh diperbaiki. Setelah dicek lagi.

2021-11-21 01:51 UTC, eddieridwan requested changes
@FirlianiF , lihat komentar apa saja yg masih perlu diperbaiki. Mohon lakukan testing secara teliti.

2021-11-21 01:51 UTC, eddieridwan commented on donjo-app/config/routes.php
> +$route['sub-gallery/(:any)'] = 'first/sub_gallery/$1/$2';
@FirlianiF ini salah. Menyebabkan tautan ke sub-gallery pergi ke halaman yg salah.

![galeri-1](https://user-images.githubusercontent.com/249563/142746164-53d72663-7305-42f4-b2e2-f4759b0f91d8.jpg)

2021-11-21 01:51 UTC, eddieridwan commented on donjo-app/controllers/First.php
> +		}
@FirlianiF , perhatikan bahwa nilai default adalah galeri pertama ($gal = 0) dan halaman paginasi pertama ($p = 1).
Jadi kalau sampai $p dikirim sebagai string kosong, maka seharusnya diubah menjadi 1, yaitu halaman paginasi pertama. Juga perhatikan aturan penulisan script, seperti dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script

2021-11-21 04:36 UTC, eddieridwan commented on donjo-app/controllers/First.php
> +		// echo 'gal = '.$gal.' dan p = '.$p;
Hapus komentar debugging.

2021-11-21 04:37 UTC, eddieridwan commented on donjo-app/controllers/First.php
> +		}
Perbaiki sesuai aturan penulisan:
1. kurung kurawal di baris tersendiri
2. spasi sebelum dan sesudah operator (mis `$p = 1`)

2021-11-21 04:42 UTC, eddieridwan reviewed
@FirlianiF , masih ada aturan penulisan yg belum sesuai. Tidak perlu anda kerjakan, tetapi perlu diperhatikan pada pengerjaan tugas berikutnya. 

**Tugas ini kita nyatakan selesai**. Pull request ini akan kami tutup.

Terima kasih telah mengerjakan.

2021-11-21 04:42 UTC, closed without merging