fix issue #3811 pada menu statis
OpenSID/OpenSID pull request #4543
Opened 2021-11-23 14:48 UTC by scqolbu24

Solusi untuk {perbaikan|fitur baru} terkait issue {#3811}

1. Menambahkan source_code pada file donjo-app>config>routes.php = 
    // Halaman statis    
    $route['gallery'] = 'first/gallery';               //ini adalah code yang ditambahkan

2. Menambahkan source_code pada file donjo-app>models>Referensi_model.php pada STAT_LAINNYA= 
    // Statistik Lainnya
    define("STAT_LAINNYA", serialize([
    ..........
	 'gallery ' => 'Gallery',                           //ini adalah code yang ditambahkan
    ]));

2021-11-23 21:28 UTC, eddieridwan requested changes
@scqolbu24 terima kasih. Ada beberapa masalah. Untuk menemukan masalah, anda perlu melakukan testing yg seksama.

1. Sekarang ternyata route `gallery` menjadi rancu, karena juga digunakan untuk membuka halaman gallery untuk admin. Sekarang menu admin `Admin Web > Galeri` salah, karena membuka halaman web. Jadi perlu menggunakan route yg berbeda untuk menampilkan gallery di web. Misalnya bisa menggunakan `web-gallery` untuk membedakan.

![galeri-1](https://user-images.githubusercontent.com/249563/142717566-fa386d05-1924-4364-8f67-918891bb2e75.jpg)

2. Tautan yg tampil di menu statis untuk gallery masih ada prefix `first`.  Seharusnya tidak. Lihat contoh untuk tautan ke peta. Cari di script di mana untuk mencegah ditampilkannya `first` untuk halaman statis seperti peta, peraturan_desa dan gallery.

![galeri-2](https://user-images.githubusercontent.com/249563/142717693-1642cdb6-a9fc-4df2-a25e-54a5843d39c5.jpg)

3. Tampilan di tema natra salah, karena layout untuk halaman statis di tema natra berbeda. Untuk menyesuaikan ini pelajari contoh untuk halaman statis lainnya pada tema natra, seperti halaman peraturan_desa.

![galeri-3](https://user-images.githubusercontent.com/249563/142717811-29f6cedf-e67f-4513-9494-3269749723dd.jpg)
![galeri-4](https://user-images.githubusercontent.com/249563/142717814-b51951ba-8e50-4606-92c5-8e08df20b364.jpg)

4. Perhatikan juga tautan di widget galeri yg juga perlu disesuaikan (termasuk hilangkan `first`).

Mohon diperbaiki. Dan lakukan testing secara seksama sebelum mengirim ulang.

Ditunggu.

2021-11-27 03:02 UTC, scqolbu24 reviewed
Perbaikan pada masalah yang baru pada issue  issue #3811 pada menu statis #4543:
1.	Issue tidak dapat membuka halaman galleri di admin
a.	Menambahkan source_code pada file donjo-app>config>routes.php = 
// Halaman Admin Web Gallery
$route[‘web-gallery’] = ‘gallery’;    //ini adalah code yang ditambahkan

b.	Mengubah sorce_code pada file donjo-app>controllers>Gallery.php agar dapat tampil di halaman admin Ketika klik menu Galleri dan dapat melakukan pencarian, filter dan insert

Pada method clear(), method search(), method filter(), method insert(),
agar dapat tampil di halaman admin Ketika klik menu Galeri
redirect(‘gallery’);
diganti :
redirect(‘web-gallery’); //ini adalah code yang diubah


2.	Issue Tautan yg tampil di menu statis untuk gallery masih ada prefix first
Menambahkan source_code pada file donjo-app>core>MY_Model.php didalam method menu_slug($url)

case ‘gallery ‘: //ini adalah code yang ditambahkan

3.	Tampilan di tema natra salah, karena layout untuk halaman statis di tema natra berbeda. 
Buka file pada themes>natra>partials>gallery.php

a.	Pada file terdapat kelebihan "div" dibaris terakhir sehingga membuat halaman salah, untuk memperbaikinya maka "div" dihapus.
b.	Kemudian ubah source_code berikut :
div style=”content_bottom_left”    Menjadi  div class=”content_bottom_left” 

4.	Perhatikan juga tautan di widget galeri yg juga perlu disesuaikan (termasuk hilangkan first).
a.	Mengubah source_code pada file donjo-app>views>gallery>form.php, Ada 2 yang diubah pada baris 6 dan 16

site_url(‘gallery’)
diganti 
site_url(‘web-gallery’)

b.	Mengubah source_code pada file donjo-app>views>gallery>sub_gallery_table.php, Ada 2 yang diubah pada baris 15 dan 31

site_url(‘gallery’)
diganti 
site_url(‘web-gallery’)

c.	Mengubah source_code pada file donjo-app>views>gallery>form_sub_gallery.php, Ada 1 yang diubah pada baris 6

site_url(‘gallery’)
diganti 
site_url(‘web-gallery’)

2021-11-27 05:46 UTC, eddieridwan requested changes
@scqolbu24, terima kasih. Tetapi solusi anda masih banyak yg perlu diperbaiki. Silakan lihat komenter.

Perhatikan bahwa anda belum melakukan testing pada semua link yg mengarah ke halaman galeri di web. Untuk semua tautan itu, perlu disesuaikan supaya tautan yg tampil tidak berisi `first`. Mohon lihat lagi komentar pada review yg sebelumnya. 

Mohon perbaiki dan kirim ulang. Ditunggu.

2021-11-27 05:46 UTC, eddieridwan commented on donjo-app/config/routes.php
> +$route['web-gallery'] = 'gallery';
@scqolbu24 , seharusnya cukup 
`$route['web-gallery'] = 'first/gallery';`
karena yg perlu disesuaikan adalah route ke tampilan galeri di web, bukan galeri di admin

2021-11-27 05:46 UTC, eddieridwan commented on donjo-app/controllers/Gallery.php
> +{
@scqolbu24 file ini sama sekali tidak perlu diubah. Karena yg disesuaikan adalah route ke tampilan galeri di web bukan ke admin.

2021-11-27 05:46 UTC, eddieridwan commented on donjo-app/views/gallery/form.php
> +			<li><a href="<?= site_url('web-gallery') ?>"><i class="fa fa-dashboard"></i> Daftar Album</a></li>
@scqolbu24 file ini sama sekali tidak perlu diubah. Karena yg disesuaikan adalah route ke tampilan galeri di web bukan ke admin.

2021-11-27 05:46 UTC, eddieridwan commented on donjo-app/views/gallery/form_sub_gallery.php
> +			<li><a href="<?= site_url('web-gallery') ?>"><i class="fa fa-dashboard"></i> Daftar Album</a></li>
@scqolbu24 file ini sama sekali tidak perlu diubah. Karena yg disesuaikan adalah route ke tampilan galeri di web bukan ke admin.

2021-11-27 05:46 UTC, eddieridwan commented on donjo-app/views/gallery/sub_gallery_table.php
> +			<li><a href="<?= site_url('web-gallery') ?>"><i class="fa fa-dashboard"></i> Daftar Album</a></li>
@scqolbu24 file ini sama sekali tidak perlu diubah. Karena yg disesuaikan adalah route ke tampilan galeri di web bukan ke admin.

2021-11-27 05:46 UTC, eddieridwan commented on donjo-app/views/web/halaman_statis/informasi_publik.php
> +  <!-- Bug? paksa kotak cari ke sisi kanan
@scqolbu24 file ini sama sekali tidak perlu diubah. Karena yg perlu disesuaikan hanya layout tema natra untuk galeri

2021-11-27 05:46 UTC, eddieridwan commented on themes/natra/partials/gallery.php
> +						<a href="<?= site_url() . "first/sub_gallery/" . $data['id'] ?>" title="<?= $data["nama"] ?>"> Album : <?= $data["nama"] ?></a>
@scqolbu24 di file ini seharusnya semua `first/sub_gallery` diganti menjadi `web-gallery`. Dan juga perlu disesuaikan di file sub_gallery, dan juga di tema klasik. Dan juga di widget Gallery.

2021-11-29 13:14 UTC, closed without merging