Statistik kehamilan
OpenSID/OpenSID pull request #4647
Opened 2022-01-02 04:31 UTC by Irvan1609

2022-01-02 06:22 UTC, andifahruddinakas commented
Mas @Irvan1609, silahkan linkkan issue yg sedang dikerjakan di PR ini.

2022-01-02 06:23 UTC, andifahruddinakas commented
Cek juga panduan https://github.com/OpenSID/OpenSID/wiki/Proses-Review-Pull-Request

2022-01-02 06:37 UTC, Irvan1609 commented
https://github.com/OpenSID/OpenSID/issues/1759

2022-01-03 01:57 UTC, andifahruddinakas commented
Terlalu banyak yg diubah tdk sesuai dengan issue??? Cukup ubah bagian yg berkaitan dengan issue ini saja.

2022-01-03 06:04 UTC, andifahruddinakas requested changes

2022-01-03 06:04 UTC, andifahruddinakas commented on hamil.sql
> +/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
Buat menggunakan migrasi

2022-01-10 08:42 UTC, andifahruddinakas commented
Sudah digabung ke `PREMIUM` melalui PR https://github.com/OpenSID/premium/pull/567

2022-01-10 08:42 UTC, closed without merging