tambah no rumah di rtm
OpenSID/OpenSID pull request #4810
Opened 2022-01-30 06:04 UTC by Irvan1609

Untuk menambahkan no rumah dapat dilakukan dengan menginputkan nilainya pada aksi edit
(https://github.com/OpenSID/OpenSID/issues/4679)

2022-02-03 12:16 UTC, andifahruddinakas commented
1. Pisah/hapus commit cd2a123857e2e511f7271e81306936f0a45d2ea0, 1 PR 1 issue.
2. Jangan ubah/hapus yang tidak berkaitan dgn issue (contoh database).

2022-02-03 12:17 UTC, andifahruddinakas requested changes
cek komentar

2022-02-05 23:13 UTC, Irvan1609 commented
sudah mas, maaf untuk tabelnya saya tambahkan satu kolom no_rumah type integer di tweb_rtm

2022-02-10 16:43 UTC, andifahruddinakas commented
PR ini sy tutup karena tidak sesuai dengan issue https://github.com/OpenSID/OpenSID/issues/4679 yang di inginkan, pada issue tsb memungkinkan adanya qrcode.

2022-02-10 16:43 UTC, closed without merging