WIP: Pengaturan slider
OpenSID/OpenSID pull request #7449
Opened 2023-11-24 14:31 UTC by arifpriadi

Issue https://github.com/OpenSID/OpenSID/issues/5141

2023-11-24 20:17 UTC, andifahruddinakas requested changes

2023-11-24 20:17 UTC, andifahruddinakas commented on donjo-app/models/migrations/Migrasi_fitur_premium_2305.php
> +        $this->db->query("INSERT INTO `setting_aplikasi` (`judul`, `key`, `value`, `keterangan`, `jenis`) VALUES ('Jumlah Gambar Slider', 'jumlah_gambar_slider', '10', 'Jumlah Gambar Slider Yang di T
migrasi ini perlu disesuaikan menggunakan cara CI3.
contoh dapat di lihat pada https://github.com/OpenSID/OpenSID/blob/umum/donjo-app/models/migrations/Migrasi_fitur_premium_2304.php#L75-L91

2023-11-25 12:50 UTC, arifpriadi commented on donjo-app/models/migrations/Migrasi_fitur_premium_2305.php
> +        $this->db->query("INSERT INTO `setting_aplikasi` (`judul`, `key`, `value`, `keterangan`, `jenis`) VALUES ('Jumlah Gambar Slider', 'jumlah_gambar_slider', '10', 'Jumlah Gambar Slider Yang di T
Sudah disesuaikan.

2023-12-15 08:14 UTC, andifahruddinakas commented
Sudah digabungkan ke rilis premium dengan perubahan, melalui commit https://github.com/OpenSID/premium/commit/4b9750cb4f8246e2cf57d3a9bd22a825fc56bdad

2023-12-15 08:14 UTC, closed without merging