WIp: Akta kematian
OpenSID/OpenSID pull request #7451
Opened 2023-11-24 14:35 UTC by arifpriadi

Issue https://github.com/OpenSID/OpenSID/issues/2612

2023-11-24 20:07 UTC, andifahruddinakas requested changes
Setelah di cek, perubahan ini tidak menghitung secara kategori umurnya. Hanya mengitung jumlahnya saja.

<img width="328" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/1b6892b6-6c00-4c45-8cc3-506d1163b121">


Saat di klik angkanya tidak mengarahkan ke halaman yang benar, yakni log_penduduk.

2024-01-12 16:18 UTC, arifpriadi commented
> Setelah di cek, perubahan ini tidak menghitung secara kategori umurnya. Hanya mengitung jumlahnya saja.
> 
> <img alt="image" width="328" src="https://private-user-images.githubusercontent.com/57283157/285538287-1b6892b6-6c00-4c45-8cc3-506d1163b121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzY1ODgsIm5iZiI6MTcwNTA3NjI4OCwicGF0aCI6Ii81NzI4MzE1Ny8yODU1MzgyODctMWI2ODkyYjYtNmMwMC00YzQ1LThjYzMtNTA2ZDExNjNiMTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE2MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MjZlY2JmMTQ4ZjEwODc3OTBlYmFjMDY2ZDEwY2M2NWY5YjZiMDcwYTM1ZjczMDIyMWEwN2JmMDk3NWE3MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z1Iwl9SjF65vkMaBw_IKhj3zpDWD3xjscHAih1oql34">
> Saat di klik angkanya tidak mengarahkan ke halaman yang benar, yakni log_penduduk.

Sudah disesuaikan, diarahkan ke log_penduduk.
<img width="497" alt="image" src="https://github.com/OpenSID/OpenSID/assets/145224165/37bbcbb2-ec8a-4a8e-8609-748129ebb1df">

2024-01-13 15:56 UTC, andifahruddinakas commented
mas @arifpriadi, mohon di resolve conflict terlebih dahulu.

2024-01-14 17:34 UTC, arifpriadi commented
> mas @arifpriadi, mohon di resolve conflict terlebih dahulu.

Sudah disesuaikan.

2024-01-16 08:57 UTC, andifahruddinakas commented
mas @arifpriadi, PR ini sudah digabungkan melalui commit  https://github.com/OpenSID/premium/commit/7c3ef1f4144c0f4d6d1f1eec0b135054ca4e57bb dengan penyesuaian yang ada di branch rilis-dev.

2024-01-16 08:57 UTC, closed without merging

2024-01-27 19:29 UTC, ariandii commented
@andifahruddinakas informasi, penerapan statistik akta kematian ini belum tampil di navigasi seperti penerapan issue:
https://github.com/OpenSID/OpenSID/pull/7140

dan judul pada halaman web juga belum tampil (setelah membuat Menu Statistik nya)

2024-01-29 05:53 UTC, andifahruddinakas commented
> @andifahruddinakas informasi, penerapan statistik akta kematian ini belum tampil di navigasi seperti penerapan issue: #7140
> 
> dan judul pada halaman web juga belum tampil (setelah membuat Menu Statistik nya)

Sepertinya kurang pada haman web

2024-01-29 06:07 UTC, ariandii commented
![IMG_20240129_130700_918](https://github.com/OpenSID/OpenSID/assets/46939846/478ce001-5b93-44ed-8a6b-ffd2865800ee)

termasuk judul di menu statistik kependudukan muncul sama di 7 statistik sesuai gambar. mulau covid sampai yg baru ini.

2024-01-29 06:33 UTC, andifahruddinakas commented
> ![IMG_20240129_130700_918](https://private-user-images.githubusercontent.com/46939846/300349985-478ce001-5b93-44ed-8a6b-ffd2865800ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDg5MzIsIm5iZiI6MTcwNjUwODYzMiwicGF0aCI6Ii80NjkzOTg0Ni8zMDAzNDk5ODUtNDc4Y2UwMDEtNWI5My00NGVkLThhNmItZmZkMjg2NTgwMGVlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA2MTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzODc5NDA0MGMzZWI4ODg5ZmEzYTY0NmZiYmVhN2QyNWY4NmE2MWFjNzdiZWEyOWZhZjBjNzhmNmI2MzQ2OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nD9KaD6_TcJCrcgP4oVLo_KzFuNUPg2LxIQPkoDvRr0)
> 
> termasuk judul di menu statistik kependudukan muncul sama di 7 statistik sesuai gambar. mulau covid sampai yg baru ini.

https://github.com/OpenSID/premium/commit/a3cbb9f73c1fb468952a8514ce9d3f2502bc9402