wip: media sosial pengurus
OpenSID/OpenSID pull request #7590
Opened 2024-01-12 14:52 UTC by arifpriadi

issue https://github.com/OpenSID/OpenSID/issues/2603

2024-01-13 14:59 UTC, andifahruddinakas requested changes

2024-01-13 14:59 UTC, andifahruddinakas commented on resources/views/admin/pengurus/form.blade.php
> +                    $sosmed = ['Facebook', 'Twitter', 'Youtube', 'Instagram', 'WhatsApp', 'Telegram'];
mas @arifpriadi, gunakan enums untuk menyimpan data ini.

2024-01-13 14:59 UTC, andifahruddinakas commented on resources/views/admin/pengurus/form.blade.php
> +                    $sosmed = ['Facebook', 'Twitter', 'Youtube', 'Instagram', 'WhatsApp', 'Telegram'];
gunakan fungsi blade {{ }}, @if, @forrech, dll

2024-01-13 15:00 UTC, andifahruddinakas commented
mas @arifpriadi, sebaiknya semua ikon media sosialnya ditampilkan walau datanya belum ada. agar kelihatan rapi tidak ada yang kosong.

2024-01-14 17:35 UTC, arifpriadi commented
> mas @arifpriadi, sebaiknya semua ikon media sosialnya ditampilkan walau datanya belum ada. agar kelihatan rapi tidak ada yang kosong.
> 
> Bisa lihat contoh : [#2603 (comment)](https://github.com/OpenSID/OpenSID/issues/2603#issuecomment-577424650)

Sudah disesuaikan dengan menggunakan data yang ada pada tabel media_sosial dibanding menggunakan enums.

2024-01-16 00:18 UTC, andifahruddinakas commented
mas @arifpriadi, PR ini sudah digabungkan melalui commit  https://github.com/OpenSID/premium/commit/6e92c18c12b1c02e82cc0eaead8d8510ed3f2362 dengan penyesuaian yang ada di branch rilis-dev.

2024-01-16 00:18 UTC, closed without merging