Issue 7855 - Accepted file type: WebP
OpenSID/OpenSID pull request #7947
Opened 2024-05-17 18:31 UTC by nyomanjyotisa

Solusi untuk issue https://github.com/OpenSID/OpenSID/issues/7855

Saya menambahkan jenis file webp pada accepted file pada file upload, total file updated 38.

2024-05-19 18:48 UTC, andifahruddinakas requested changes
mas @nyomanjyotisa, cek komentar.

2024-05-19 18:48 UTC, andifahruddinakas commented on vendor/codeigniter/framework/system/libraries/Image_lib.php
> +			if ( ! preg_match('#\.(jpg|jpeg|gif|png|webp)$#i', $this->new_image))
mas @nyomanjyotisa, jangan mengubah bagian folder vendor secara langsung. karena akan terhapus jika melakukan update package.

Bisa lakukan dengan overwirde librarinya saja. contoh: https://github.com/OpenSID/OpenSID/blob/umum/donjo-app/libraries/MY_Form_validation.php, https://github.com/OpenSID/OpenSID/blob/umum/donjo-app/libraries/MY_Upload.php

2024-05-19 18:48 UTC, andifahruddinakas commented on donjo-app/controllers/Identitas_desa.php
> +            'allowed_types' => 'gif|jpg|jpeg|png|webp',
untuk mempermudah perbubahan, bisa lakukan difined di 1 tempat untuk ekstention yang berupa gambar, contoh : 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/abde96fb-4581-4195-b7f7-2431cd9a0cd3)

https://github.com/OpenSID/OpenSID/blob/umum/donjo-app/helpers/pict_helper.php#L75-L77

2024-05-22 11:29 UTC, nyomanjyotisa commented
Halo mas @andifahruddinakas , sudah saya update sesuai dengan kedua komentar. Mohon direview kembali. Terima kasih.

Regards,
I Nyoman Jyotisa

2024-06-11 08:04 UTC, andifahruddinakas commented
mas @nyomanjyotisa, bisa hubungi mas @vickyrolanda agar bisa berkontribusi di repo private. krn saat ini PRnya sudah berbeda dengan yg ada pada repo pengembangan.

2025-03-27 16:38 UTC, andifahruddinakas commented
PR ini sudah tidak relevan

2025-03-27 16:38 UTC, closed without merging