Issue 7853 - Meta Description dan Meta Keyword untuk Keperluan SEO
OpenSID/OpenSID pull request #7948
Opened 2024-05-18 01:36 UTC by nyomanjyotisa

Solusi untuk issue https://github.com/OpenSID/OpenSID/issues/7853

Summary:
- Migration untuk menambahkan fields terkait di tabel artikel

- Pengaturan SEO pada halaman tambah dan ubah artikel
![image](https://github.com/OpenSID/OpenSID/assets/73281575/e9ff42ef-e3e2-4677-9e3e-4c13e86b7dcb)

- Implementasi pengaturan SEO pada meta tag
![image](https://github.com/OpenSID/OpenSID/assets/73281575/dc96511d-7ecc-42ce-b906-006ba20aa1d7)

Regards,
I Nyoman Jyotisa

2024-05-19 18:51 UTC, andifahruddinakas requested changes
mas @nyomanjyotisa, cek komentar.

2024-05-19 18:51 UTC, andifahruddinakas commented on donjo-app/models/migrations/Migrasi_fitur_pengaturan_seo_pada_artikel.php
> +        $this->dbforge->add_column('artikel', $fields);
mas @nyomanjyotisa, lakukan pengecekan pada kolom yang akan ditambahkan apakah ada atau tidak, jika belum ada maka baru tambahkan.

Karena di OpenSID menerapkan migrasi berulang, maka akan terjadi error jika tidak ada pengecekan terlebih dahulu.

2024-05-20 10:26 UTC, nyomanjyotisa commented
Halo mas @andifahruddinakas , sudah saya tambahkan pengecekan kolom yang akan ditambahkan. Mohon direview kembali. Terima kasih.

Regards,
I Nyoman Jyotisa

2024-05-22 10:56 UTC, nyomanjyotisa commented on donjo-app/models/migrations/Migrasi_fitur_pengaturan_seo_pada_artikel.php
> +        $this->dbforge->add_column('artikel', $fields);
Halo mas @andifahruddinakas , sudah saya tambahkan pengecekan kolom yang akan ditambahkan. Mohon direview kembali. Terima kasih.

Regards,
I Nyoman Jyotisa

2025-05-02 06:25 UTC, closed without merging